### ISSUE TITLE
SDKs development configuration improvements

### ISSUE THREAD

**Issue by kumpera** [mono/mono#10376]
This is a list of small improvements I think we could do to the SDKs to improve our quality-of-life when using it as a way to work on non-desktop targets:

- [ ] Add a configure-style script (being discussed in #10239)
- [ ] An option to disable llvm usage by ios/android/wasm *1
- [ ] Audit and document all external properties that can be used to control the SDKs behavior *2 *3
- [ ] Ensure that configuring for nothing builds nothing
- [ ] Add high level targets in `sdks` that go together with `configure` to build/test the whole thing
- [ ] Transition CI to use the mono-team-friendly targets as a way to ensure they don't regress
- [x] Cleanup the llvm targets so they have consistent output directories *4 - https://github.com/mono/mono/pull/10445 https://github.com/mono/mono/pull/10427 https://github.com/mono/mono/pull/10398

Notes:
- 1 This would mean no AOT under wasm, we can debate later
- 2 By audit I mean ensure positive flags don't start as negatives, I.E. IGNORE_PACKAGE_LLVM
- 3 Bonus point if all of them are integrated into configure
- 4 It's confusing that wasm uses `ios-llvm32` and `make package llvm-lvm32` leaves an empty `out/llvm-llvm32`

**Comment by kumpera** [comment]
cc @luhenry @vargaz 
I'm volunteering for doing all of this work and whatever else comes up, btw.

**Comment by kumpera** [comment]
This is from a discussion with @alexischr on #mono-community.

If we use `--enable-llvm` instead of `--with-llvm=` to sprinkle llvm into our build, it uses `llvm/llvm.mk` directly, which leaves build artifacts in that place.

Maybe instead of the convoluted relation between this and the SDKs we could just have it ask the SDKs for the right llvm and be done with it.

**Comment by luhenry** [comment]
I am right now at work to unify a bit more how we provision LLVM for iOS and Android. I would make what's necessary for WASM to use it, so I would need to understand better how WASM uses it.

For the `llvm/build/mk` vs `sdks/builds/llvm.mk` question, it was decided when we did it for the latter to depend on the former (and not the other way around), so the source of truth for how Mono builds LLVM is in `llvm/build.mk` which is easier to use than `sdks/builds/` from the Mono sources. That's mostly because we do **not** want to have automake involved in `sdks/` while we still need to pass parameters from `configure.ac` to `llvm/Makefile.am`.

Finally, regarding the configure script, the only constraint I have is I don't want to have XA and XI need to run the `sdks/configure` script before being able to use the build targets. That's because these products do not necessarily want to build all the runtimes (because of build time constraints), and they can just cherry-pick which runtime to build by invoking directly the appropriate `package-*` rule.
That constraint doesn't go against the configure script idea, and they are both complementary.

For the CI, what do you mean by "mono-team-friendly"? `./sdks/configure --enable-android --enable-ios --enable-wasm && make -C sdks package` or `make -C sdks/builds package-android-{...} package-ios-{...} package-wasm-{...}`?

**Comment by kumpera** [comment]
On having XI/XA calling specific targets, I think that's a mistake as it exposes a bigger, harder to constraint surface than actually is needed, but that's up to you.

What do I mean mono-team friendly? Friendly for us to work with the SDKs not just as a means to delivery bits to the XI/XA. Remember that one of the goals of this effort is enable us to work with iOS and Android without having to deal with them at all.

In my case, I'd like to have this to to get us to the wasm test suite running:
```
./sdks/configure --enable-wasm
make -C sdks build test
```

**Comment by jaykrell** [comment]
I find the sdks model a bit foreign as well, but I wonder if maybe it isn't better? I mean, isn't/shouldn't-be wasm just a different target? Isn't lack of configure a good thing? It is kind of an even better form of out-of-tree build -- all targets already configured, and all buildable in their own directories.

Maybe you mean make sdks-wasm build-wasm test-wasm?

**Comment by kumpera** [comment]
Hi @jaykrell thanks for your feedback on makefile target names.

**Comment by luhenry** [comment]
@kumpera my vision for the SDKs is to get us to a point where we can have a binary dependency (and not a source dependency) for the products, while still having the possibility for them to build from source. We could then imagine giving them a "package" with everything and remove the possibility to pick specific targets, but until then it would be quite wasteful for them to have to build all runtimes even if the only thing they care about is `android-x86` for the simulator for example.

Also, that is also not contradictory to having friendly APIs for our own use cases. I do like a lot the idea of being able to do `./sdks/configure --enable-wasm; make -C sdks build test`, as it's been already requested a few times on various Issues by external contributors.

What I would also love to see it to be able to do `make check-{android,ios,wasm} -C mcs/class/corlib` and this takes care of most things (building the tests, pick the runtime, deploy+run the app, and fetch the results). All these improvements will most likely be very incremental, and things will change as we go. We should not expose them "publicly" so we do not get stuck in the API, allowing us to organically evolve.

Should we discuss the use cases we want, so we can work on common goal? As far as I understand, we so far only have a list of feature, and not a clear description of why we want them. Could you (@kumpera, @vargaz, anybody else who would like to have any use it) describe in details some use-cases you want/have, I'll prepare something and post it here. I will mostly be focused around Android (since that's what I have spent most of my time on), but it should be generalizable to iOS and WebAssembly as well. In short, please describe your vision so we can all align on the same thing.

**Comment by kumpera** [comment]
Hmmm, your approach with the SDKs now makes a lot more sense.

On moving forward, I think having a clear set of goals gets us the north we need to progressively find ways to achieve them. This issue and the list of suggestions on it further us a bit.

Here are the goals (project chapter) I see for the SDKs effort:

For embedders (XI/XA), they should be able to consume mono without caring for how it's built and what dependencies it has. They should be able to drive source and binary builds using the same bootstraping code by simply changing a flag. The build scripts interface should be minimal, stable and tested.

For mono developers, we should be able to work on our day-to-day targets with ease. The SDKs should drive productivity in the form of easier on-boarding/setup, faster build times and streamlined provisioning/deployment/debugging/testing. It should be very opinionated and consistent to facilitate our communication.

From there we can skim/prioritize tasks as time progresses. I feel like there's enough exploration nature to this effort that planning more than one or two steps ahead would be wasteful. I like daydreaming about the future but, right now, the above is how far I see the SDKs lacking in terms of the second goal. Once we have it, I'll use enjoy them and find the next step of pain points.

**Comment by luhenry** [comment]
To complement the work for the mono developers, I want to have the possibility to run Android and iOS apps solely focused on running the BCL tests without XA and XI. In achieving that, I also want to make it easier for anyone to easily embed Mono into their app (Android and iOS) by simply copy/pasting how we do it for the test app.

This implies a few things:
 - our testing apps should be quite idiomatic Android and iOS projects, the Android one should be a Android Studio project for example
 - the Mono SDKs should provide all thats necessary to easily build and run Mono embedded into an existing native app. For example, give the user a `ContentProvider` on Android which takes care of loading `libmonosgen-2.0`, initialize it and give the user the possibility to easily call Java code from C# (Java.Interop). In that effort, we have no value in replacing XI and XA, since they provide much more than we care about (Bindings, IDE integration, etc.). This effort cannot go contrary to them, but has to be complementary to what they do: we would be more involved in how Mono runs on device and we would do no Binding or IDE integration work, we would simply provide documentation for how to embed Mono into an existing Android and iOS app.

The second point is what has motivated me to move code supporting the BCL from XA into Mono, as well as invert the loading between `libmonodroid` and `libmonosgen-2.0` (right now, the former loads the latter, while I want it the other way around). These two effort would IMO help us in 1. test and run Mono on devices ourselves, and 2. provide the community with an easier way to embed Mono into their existing native apps.
