### ISSUE TITLE
C++ codebase

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#10769]
We want to explore what it would take for us to allow C++ to be used in Mono and put together a plan to allow Mono first to be compiled with C++ and then to start using some C++ on it.   Mono already links with C++ when using LLVM.

The intent is not to start an effort to rewrite existing working code into C, nor to launch ourselves into gratuitous refactoring efforts, but rather to allow us to use C++ when it would be beneficial for agility, maintenance or robustness.

For more detailed proposal see https://paper.dropbox.com/doc/Mono-and-C-Proposal--ANm1M7eRCset~1CQ~YrqehUtAg-Hyw1zqWef6QOhDV2Vcazd

## Milestone I

- [x] Make existing codebase compatible with C++ compilers
- [ ] Introduce C++ only lane to ensure we don't regress
- [ ] Make a catalog with issues and workaround we found when making the code compatible
- [ ] Ensure resulting C++ binaries work and pass all tests

## Future
- [ ] Determine what minimal C++ version we want to support

## Proposals of new features which could benefit from C++ 
* Coop
	- manual codeflow for releasing resources on every icall;
	- the handles are not type-safe, are error-prone, lots of code duolication
	- C++ automatic calling of festructors (RAII)
	- templates for the types

**Comment by lambdageek** [comment]
We have C++ Linux/OSX/Windows master and PR lanes - both compiling and running test suites.
SDK PR lanes on-demand for the moment.
