### ISSUE TITLE
2018-10 Mono Release

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#10981]
# Products integration

## Visual Studio for Mac

Integrator: @kg 

Pull Requests:
 - [ ] https://github.com/xamarin/md-addins/pull/3666

## Xamarin Designer

Integrator: @kg 

Pull Requests:
 - [ ] https://github.com/xamarin/designer/pull/1351

## Xamarin.Android

Integrator: @alexischr

Pull Requests:
- [x] https://github.com/xamarin/xamarin-android/pull/2253
- [x] https://github.com/xamarin/monodroid/pull/860

Wrench:
 - https://wrench.internalx.com/Wrench/index.aspx?lane=monodroid-mavericks-mono-2018-10

## Xamarin.iOS

Integrator: @akoeplinger 

Pull Request:
- [x] https://github.com/xamarin/xamarin-macios/pull/4904

Wrench:
 - https://wrench.internalx.com/Wrench/index.aspx?lane=macios-mac-mono-2018-10

# Releasing Checklist

## Nightly

None

## Preview

Published daily from monthly branch once Visual Studio for Mac has been successfully integrated

- [ ] Release notes preview is available on the [website](https://github.com/mono/website/tree/gh-pages/docs/about-mono/releases)

## Stable
Published weekly from the monthly branch once the integration of the products has been completed successfully.

- [ ] Publish macOS .pkg and Windows .msi to the download server in the stable channel
- [ ] Publish Linux packages to the package repository in the stable channel
- [ ] Update the [Mono Docker](https://github.com/mono/docker) image and send a PR to Docker
- [ ] Publish mkbundle runtime
- [ ] Verify tarball exists on the download server
- [ ] Remove Preview note from the release notes
- [ ] Send an announcement email to "Xamarin - Release Threads xamareth@..."
- [ ] Check a tag for the release exists on GitHub
