### ISSUE TITLE
Add Entity Framework Core tests

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11155]
Xamarin customers are experiencing occasional issues when using EF Core on Xamarin. The issues can be split into two buckets.

1. Linker related
2. AOT related

For the long-term stability, we need to figure out how to run EF Core tests on Helix as part of our CI. This is something that we’ll do only after we can run the tests manually.

## Milestone I
- [ ] Add EF tests from stable release available at https://github.com/aspnet/EntityFrameworkCore/tree/master/test to our CI
- [ ] Add customer (probably just sample code) EF tests to linker scenario testing (new repo).

## Future
- [ ] Run the tests at least partially on our SDKs lane
- [ ] Figure out how to run the tests on the device or setup which is close to iOS device

**Comment by cwrea** [comment]
Wanted to say that I appreciate this being looked at on the Xamarin side of things. Thank you!

Here's a related issue from the EF repository, with relevant discussion: [aspnet/EntityFrameworkCore - Add testing for Xamarin #8792](https://github.com/aspnet/EntityFrameworkCore/issues/8792).

Earlier this year I tinkered with the EF test suite on Xamarin and got a relevant subset compiling and running on device for both Android and iOS. [See here](https://github.com/cwrea/EFCoreCPTestSoln/tree/EFCore2.0.2_VS15.7). The work is somewhat stale now, but does support the characterization of many remaining issues as AOT-related. I'll also mention [this Xamarin Forums discussion](https://forums.xamarin.com/discussion/95916/works-xamarin-forms-net-standard-entity-framework-core-for-sqlite-on-ios-android-uwp), re: linker-related issues encountered when trying to get applications using EF Core working on device.

Thank you!

🙏 🙏
