### ISSUE TITLE
Update default interfaces support

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11267]
We need to refresh our default interface support to align with the latest runtime change mostly about diamond scenarios and constrained/boxed calls

## Actions
- [ ] Update tests to include the latest change from CoreCLR
- [ ] Add System.Reflection support for dim with tests (see https://github.com/dotnet/coreclr/pull/16257)
- [ ] Add System.Reflection.Emit support for dim (see https://github.com/dotnet/coreclr/pull/16034)

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/13154

**Comment by vargaz** [comment]
The only failing test is  constrained2.il, not sure how that test is supposed to work.

**Comment by MichalStrehovsky** [comment]
> The only failing test is constrained2.il, not sure how that test is supposed to work.

@vargaz Can you double check you ran all the tests? In light of #13401 I would expect [this test](https://github.com/dotnet/coreclr/blob/master/tests/src/Regressions/coreclr/16123/ambiguousconstraint.il) to fail too because Mono is throwing the old exception for ambiguous dispatch (before the new exception [got approved](https://github.com/dotnet/coreclr/pull/21564#discussion_r242536002)).

Cc @AlekseyTs
