### ISSUE TITLE
Binary Artefacts for SDKs

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#11397]
It was requests for us to provide binary artefacts to have clearer boundarious between Mono and Xamarin SDKs. This will also eventually help us to speed up the whole build process and ultimately reduce integration time need for us to bump Mono dependencies in the products.

This issue is tracking progress on the integration of #6862 output to the Xamarin products. Additional meeting notes can be found [here](https://paper.dropbox.com/doc/Mono-Build--AQOzHhFS_meMEWLZqOuNboKeAg-nn2BQyZo76K1a5R4vD94U).

Issue https://github.com/mono/mono/issues/11719 tracks more details.

# Integration Progress

## Xamarin.Android Changes
- [x] Mono SDK integrated into build
- [x] Runtime binaries for each platform
- [x] Cross compilers
- [x] Copy only all BCL assemblies (depends on #7192)
	- [x] Mono.Posix.dll https://github.com/xamarin/xamarin-android/issues/2597 
	- [x] Mono.Data.Sqlite.dll https://github.com/xamarin/xamarin-android/issues/2407
	- [x] Switch to prebuilt System.Drawing.Primitives.dll
	- [x] Switch to prebuilt netstandard.dll
	- [x] Switch to prebuilt System.Net.Http
- [x] Copy only nunit tests assemblies
- [x] Copy only xUnit tests assemblies
- [ ] Use nunit/xunit category/trait excludes from a common place
- [x] Stop building mono-api-info.exe https://github.com/xamarin/xamarin-android/pull/3039
- [x] Stop building mono-api-html.exe https://github.com/xamarin/xamarin-android/pull/3039
- [x] mono/external/linker/ sources are included in Xamarin.Android.Build.Tasks.dll
- [x] mono/mcs/tools/pdb2mdb/ sources are included in Xamarin.Android.Build.Tasks.dll https://github.com/xamarin/xamarin-android/pull/3147
- [x] mono/support/zlib-helper.c, mono/support/nl.c sources are included into libmono-android*.so

## Xamarin.iOS Changes
- [x] Mono SDK integrated into build
- [x] Runtime binaries for each platform
- [x] Move `@rpath` logic from xamarin-macios to mono for profiler and mono-native
- [x] Add mono framework & dylib bits to package (see instructions from Rolf)
- [x] Cross compilers
- [x] Copy only all BCL assemblies (depends on #7192)
	- [x] Switch to prebuilt System.Drawing.Primitives.dll
	- [x] Switch to prebuilt netstandard.dll
	- [x] Remove System.Drawing sources from Xamarin.iOS, Xamarin.TVOS, Xamarin.WatchOS
	- [x] Switch to prebuilt System.Net.Http
- [x] Copy only nunit tests assemblies
- [x] Copy only xUnit tests assemblies
- [x] Use nunit/xunit category/trait excludes from a common place (see e.g. https://github.com/xamarin/xamarin-macios/pull/5455 for the duplication)
- [x] Stop building mono-api-info.exe
- [x] Stop building mono-api-html.exe
- [x] mono/support/zlib-helper.c sources are included
- [x] llc + opt?
- [x] Add file with Mono major.minor.build version to the archive
- [x] Figure out solution for the "installed sources" that ship with XI/XM (e.g. download them from github during the build?) --> decided to embed sources in the archive until VSMac supports sourcelink
- [x] Add `Mono.Cecil.Pdb.dll` to the zip archive (or remove need for the library from xamarin-macios, doesn't seem to be used)
- [x] Stop using sources from mono/external/cecil/
- [X] ~Stop using sources from mono/external/linker/~ --> will do later
- [X] ~Stop using sources from mono/external/nunit-lite/~ --> will do later
- [X] ~Remove need for .ignore files for tests in xamarin-macios (we should ignore tests for each platform in mono)~ --> tracked at https://github.com/mono/mono/issues/13641
- [x] On XI side: switch over to binary artifacts --> https://github.com/xamarin/xamarin-macios/pull/6097

## Xamarin.Mac Changes
- [x] Mono SDK integrated into build
- [x] Runtime binaries for each platform
- [x] Move `@rpath` logic from xamarin-macios to mono for profiler and mono-native
- [x] Add mono framework & dylib bits to package (see instructions from Rolf)
- [x] Copy only all BCL assemblies
	- [x] Remove System.Drawing sources from Xamarin.Mac
    - [x] Switch to prebuilt System.Net.Http
- [x] AOT compilers
- [x] Copy only nunit tests assemblies
- [x] Copy only xUnit tests assemblies
- [X] ~Stop using sources from mono/external/linker/~ --> will do later
- [x] On XM side: switch over to binary artifacts --> https://github.com/xamarin/xamarin-macios/pull/6097

**Comment by vargaz** [comment]
Wrt ios, the reason this was not done for the device runtimes was that ios needs tight control over the xcode versions used to build the device runtimes, which was only possible if they were built from source during the xamarin.ios build. The cross compilers and the bcl are less sensitive to this.

**Comment by alexischr** [comment]
Regarding `mono-api-info.exe` and `mono-api-html.exe` on Xamarin.Android, there two things to do:

* [sdks] Add mono-api-html.exe and mono-api-info.exe -> https://github.com/mono/mono/pull/14158 (WIP)
* Point https://github.com/xamarin/xamarin-android/blob/82881e38474f9157a2fcd57244f695f820561a22/tests/api-compatibility/api-compatibility.mk to the archive copies
