### ISSUE TITLE
Make the fullAOT+interp pass all BCL tests

### ISSUE THREAD

**Issue by lewurm** [mono/mono#11566]
Similar to https://github.com/mono/mono/issues/7053. For all assemblies include both add xunit and nunit versions.

- [ ] mscorlib
- [ ] mscorlib / xunit
- [ ] Mono.Debugger.Soft
- [ ] Mono.Profiler.Log
- [ ] System.Core
- [ ] System.Core / xunit
- [ ] System.Xml
- [ ] System.Numerics
- [ ] System.Numerics / xunit
- [ ] Microsoft.CSharp
- [ ] Microsoft.CSharp / xunit
- [ ] System.Security
- [ ] System.Security / xunit
- [ ] System
- [ ] System / xunit
- [ ] System.Data
- [ ] System.Data / xunit
