### ISSUE TITLE
Developer-Driven Numeric Lowering (Approximating deriving from Int32)

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#11986]
## Motivation:

A huge amount of time is currently being spent trying to get existing logic (business or numeric) to run in environments with radically different numerical semantics. They want to run on the GPU or an ASIC/accelerator of some kind. They want to use a microcontroller and need to make all reads for certain ints go through pinvokes. They want their int-rich code to actually emit a lot of straight-line steps to an LLVM emitter, to make a tracing JIT. They want homomorphic encryption on some ints. They want to make it use DiffSharp, to make their ray tracer be differentiable. They want to make their code emit an ONNX network, so it can run as a part of another neural network pipeline. 

They want to take a function from a bit of existing code somewhere that takes an int, and they want to pass it a type that overrides all of the operations on an integer to do something very different.

This conflicts with the semantics of the host language. You cannot derive from int. In order to overcome that, I think it is worth investing a modest amount of time to make a .NET IL rewriter that can do such automatic numeric lowering. 

The implementer would need a constructor that takes an int, and would need to annotate methods to indicate that they are overloading the relevant primitives. 

## Tasks:

- [ ] Create IL rewriter tool that is usable from within a running application using SRE
- [ ] Create interface for indicating a local or an argument that is to be rewritten.
- [ ] Write transformation passes
-- [ ] Do dataflow per method to rewrite relevant primitive operations with calls to the relevant methods (interface methods can use [AggressiveInlining] where needed)
-- [ ] Tracking called methods that now take the annotated types to also rewrite

- [ ] Create simple harness around peano arithmetic (axioms and a few complex expressions) to ensure that interface implementers satisfy a basic level of correctness. 

## Proposed Example Interface Implementers:

- [ ] Automatic differentiation (http://diffsharp.github.io/DiffSharp/)
- [ ] Open Neural Network Exchange format Emitter (https://github.com/dotnet/machinelearning)
- [ ] Computation Over Encrypted Integers (https://github.com/Microsoft/SEAL)
- [ ] System.Numerics.Vectors / System.Numerics.Matrix4x4 (https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector?view=netcore-2.2)

## Design Refinements:

- [ ] In order to debug this IL program without disassembly, we want to index back to source. One approach is to compute the sequence points before emitting, and preserve their location in the emitted IL.
- [ ] Need to stabilize the interface design. How will attributes be tagged? How to makes this feel consistent with other usage of SRE.
