### ISSUE TITLE
2019-02 Mono Release

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#12846]
# Products integration

## Visual Studio for Mac

Integrator: @kg

Pull Requests:
~- [ ] https://github.com/xamarin/md-addins/pull/4169~
 - [x] https://github.com/xamarin/md-addins/pull/4702

## Xamarin Designer

Integrator: @kg 

Pull Requests:
~- [ ] https://github.com/xamarin/designer/pull/1634~
 - [x] https://github.com/xamarin/designer/pull/2079

## Xamarin.Android

Integrator: @alexischr

Pull Requests:
- [x] https://github.com/xamarin/xamarin-android/pull/2701
- [x] https://github.com/xamarin/monodroid/pull/927

## Xamarin.iOS

Integrator: @akoeplinger 

Pull Request:
- [x] https://github.com/xamarin/xamarin-macios/pull/5563

# Releasing Checklist

## Nightly

None

## Preview

Published daily from monthly branch once Visual Studio for Mac has been successfully integrated

- [x] Release notes preview is available on the [website](https://github.com/mono/website/tree/gh-pages/docs/about-mono/releases)

## Stable
Published weekly from the monthly branch once the integration of the products has been completed successfully.

- [ ] Publish macOS .pkg and Windows .msi to the download server in the stable channel
- [ ] Publish Linux packages to the package repository in the stable channel
- [ ] Update the [Mono Docker](https://github.com/mono/docker) image and send a PR to Docker
- [ ] Publish mkbundle runtime
- [ ] Verify tarball exists on the download server
- [ ] Remove Preview note from the release notes
- [ ] Send an announcement email to "Xamarin - Release Threads xamareth@..."
- [ ] Check a tag for the release exists on GitHub

**Comment by directhex** [comment]
Designer is being tracked in https://github.com/xamarin/designer/pull/2079 which avoids changes which broke testing older non-Mojave xcodes

**Comment by steveisok** [comment]
@alexischr It looks like https://github.com/xamarin/monodroid/pull/927 has been resolved.  Can you please confirm?

**Comment by alexischr** [comment]
@steveisok confirmed (Xamarin Android integration no longer needs the monodroid bump PR)

**Comment by MattL0** [comment]
what is it missing for the 6x release?
