### ISSUE TITLE
MonoAssembly/MonoImage multi-domain (and ALC) correctness

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#13891]
The goal of this project is to stop sharing `MonoImage` between multiple domains.  Our current design is wrong.

Rght now there's a subtle bug in how Mono images behave when they're loaded in multiple domains (and there will be more problems once we're support `AssemblyLoadContext`):
If an image `A` is loaded in two domains, it is possible for the references from `A` to be resolved in two different ways in the two domains, however Mono stores a single `MonoAssembly*` for each `image->references[i]`.

What we need to do:

### Done:
- [x] Create a new `MonoImageStorage` data structure that will be responsible for the mmap'd data of a loaded assembly. → ~#13892~ reverted; #13942 
   - [x] fixup the win32 `FreeLibrary` on image close that should be done in the storage destructor
   - [x] leave `MonoImage:raw_data` as an alias to the storage raw data - would fix the extensions build, too.

### `AssemblyLoadContext` in netcore:
- [x] Stop sharing `MonoImage`s across domain or ALC boundaries.  Cache `MonoImage` loading in `MonoAssemblyLoadContext` and leave all the raw_data sharing to `MonoImageStorage` #15527
   - [x] Implement default `MonoAssemblyLoadContext` (done in #15527)
   - [x] Implement custom assembly load contexts (partly in #15527, some APIs will need more work.).

### Future / Nice to have:
- [ ] (Mono framework) Some kind of `MonoAssemblyLoadContext` support in non-netcore mono.  This will have compromises because a lot of the existing Mono API is not ALC aware (in particular - many `MonoImage` loading APIs assume a global set of loaded images).

We will do this in several steps to split up the refactoring step (adding MonoImageStorage) from the behavioral change (unsharing MonoImages).

**Comment by srxqds** [comment]
it can support multiple domain or alc in android or ios platfroms when this task complete?
