### ISSUE TITLE
Epic: Cross platform BCL builds

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#14333]
Now that `mscorlib` and `System` depend on `System.Native` on non-windows platform, our BCL is no longer portable across platforms - a BCL built for macOS cannot simply be copied across to a Windows machine and expected to run.  The interop code in a windows-specific build will directly P/Invoke into the Win32 APIs, whereas the interop code on other platforms delegates to `System.Native` which has internal calls to a platform specific native library `libmono-native.{so,dylib}`.  Moreover it is merely a matter of coincidence that, for example, Android and macOS have the same symbols with the same semantics in their `libmono-native` - they could potentially diverge to take advantage of platform-specific capabilities.

Products such as Android Designer on  Windows have the goal of running "the true monodroid BCL" profile.  Currently they achieve that by copying the monodroid-targeted-at-Android BCL to Windows and running a host Mono runtime there.  For reasons outlined above, this will no longer work.

## Tasks: ##
* [ ] Make the `monodroid` profile not assume that it is running on Android; or make a new `monodroid_designer` profile that is multi-platform by design.
* [ ] Add to our BCL build infrastructure the ability to separate the build and host platforms (build - where the BCL compilation is happening; host - the platform where the resulting BCL will run).
* [ ] Add testing infrastructure that can consume cross-platform compiled BCL profiles and run them on their designated host platform.

**Comment by lambdageek** [comment]
What I've learned today: if you build mono with `--enable-monodrdoid` it takes a hard dependency on `zlib`.  As far as I can tell it only works with an external zlib (at least the way that `sdks/builds/android.mk` is set up).

It's not a problem right now, because for just the BCL build we don't need to compile with `--enable-monodroid` (which controls the runtime's support for XA; `--with-monodroid` or explicitly building the BCL with `build_profiles='monodroid'` is what builds the BCL), but if we start doing host builds on Windows, we will need to install `mingw64-x86-64-zlib` on Cygwin on CI.
