### ISSUE TITLE
Epic: .NET 5 APIs

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#14788]
This is an umbrella epic for tracking and prioritization of .NET 5 APIs tasks. It's focusing primary on System.Private.CoreLib assembly which is the only glue assembly we'll need to hook the runtime implementation.

## Priority I
- [x] System.Environment
	 - [x] FailFast #14827
- [x] System.GC
	- [x] AllocateUninitializedArray - #15235
	- [x] GetAllocatedBytesForCurrentThread #8397
	- [x] GetGCMemoryInfo #15236
	- [x] GetTotalAllocatedBytes #15237
- [x] System.IO.Stream
	- [x] HasOverriddenBeginEndRead #17237
	- [x] HasOverriddenBeginEndWrite #17237
- [x] System.Monitor
	- [x] LockContentionCount #14828
- [x] System.Runtime.InteropServices.NativeLibrary #17369 
	- [x] LoadLibraryByName
	- [x] LoadByName
	- [x] LoadFromPath
	- [x] FreeLib
	- [x] GetSymbol
- [x] System.Runtime.InteropServices.GCSuppressTransitionAttribute ##17367
- [x] System.Runtime.Loader.AssemblyDependencyResolver #15723 
	- [x] ResolveAssemblyToPath
	- [x] ResolveUnmanagedDllToPath
- [x] System.Runtime.Loader.AssemblyLoadContext
	- [x] InternalLoadUnmanagedDllFromPath #16525 
	- [x] InternalLoad
	- [x] GetLoadedAssemblies
	- [x] GetLoadContext
- [x] System.Threading.EventWaitHandle
	- [x] CreateEventCore
- [x] System.Threading.RegisteredWaitHandle
	- [x] Wait
- [x] System.Threading.Thread
	- [x] CurrentOSThreadId #15728
	- [x] GetCurrentProcessorId #18450
	- [x] ResetThreadPoolThread
- [x] System.Threading.ThreadPool
	- [ ] ~~BindHandle~~
	- [x] KeepDispatching
	- [x] PendingUnmanagedWorkItemCount - #16076 
	- [x] ThreadCount - #16076
	- [x] UnsafeQueueNativeOverlapped
- [x] System.TypedReference - #16518 
	- [x] SetTypedReference
- [x] System.Exception
	- [x] SetCurrentStackTrace

## Priority II
- [x] System.Reflection.Emit.AssemblyBuilder
	- [x] GetReferencedAssemblies - https://github.com/dotnet/runtime/pull/36346
	- [x] GetSatelliteAssembly - https://github.com/dotnet/runtime/pull/36589
- [x] System.Reflection.Emit.DynamicMethod
	- [x] ReturnTypeCustomAttributes - https://github.com/dotnet/runtime/pull/38298
- [x] System.Reflection.Emit.ModuleBuilder
	- [x] GetFieldToken - https://github.com/dotnet/runtime/pull/37497
- [x] System.RuntimeAssembly
	- [x] IsCollectible - #15142 - https://github.com/dotnet/runtime/pull/34038
- [x] System.Runtime.InteropServices
	- [x] DllImportSearchPath - #17629 https://github.com/dotnet/runtime/pull/38975
	- [x] UnmanagedCallersOnlyAttribute - #17479
- [x] System.AppDomain
	- [x] ResourceResolve - https://github.com/dotnet/runtime/pull/36658
	- [x] FirstChanceException - https://github.com/dotnet/runtime/pull/36658

## Priority III
- [ ] System.Diagnostics.Debugger
	 - [ ] Launch
- [ ] System.Exception
	 - [ ] CreateSourceName
- [ ] System.GC
	 - [ ] _RegisterForFullGCNotification
	 - [ ] _CancelFullGCNotification
	 - [ ] _WaitForFullGCApproach
	 - [ ] _WaitForFullGCComplete
	 - [ ] StartNoGCRegion
	 - [ ] EndNoGCRegion
- [ ] System.Reflection.Emit.DynamicILInfo
	- [ ] GetTokenFor
	- [ ] SetExceptions
	- [ ] SetLocalSignature
- [ ] System.Reflection.Emit.ILGenerator
	- [ ] UsingNamespace
- [ ] System.Reflection.Emit.MethodBuilder
	- [ ] Signature
- [ ] System.Reflection.Emit.ModuleBuilder
	- [ ] GetSignatureToken
- [ ] System.Reflection.Emit.SignatureHelper
	- [ ] GetPropertySigHelper
	- [ ] AddSentinel
- [ ] System.Reflection.Metadata.AssemblyExtensions
	- [ ] TryGetRawMetadata
- [ ] System.Threading.Overlapped
	- [ ] AsyncResult
	- [ ] EventHandle
	- [ ] EventHandleIntPtr
	- [ ] OffsetHigh
	- [ ] OffsetLow
	- [ ] Pack
	- [ ] Unpack
	- [ ] UnsafePack
- [ ] System.Threading.ThreadPoolBoundHandle
	- [ ] Handle
	- [ ] AllocateNativeOverlapped
	- [ ] BindHandle
	- [ ] GetNativeOverlappedState

**Comment by filipnavara** [comment]
Things I am aware of:
- AssemblyLoadContext (likely to be split into subtasks; the static events are quite separate from the unloadable assemblies)
- NativeLibrary (CoreRT has fairly good managed implementation but it will need to be ported and wired up)

**Comment by alexischr** [comment]
I think https://github.com/mono/mono/issues/19775 should be mentioned here, though not technically an API deficiency

**Comment by alexischr** [comment]
ILGenerator is actually missing UsingNameSpace() (corrected the list). UsingNamespace() itself needs scope support (currently our BeginScope() and EndScope() are no-ops)

**Comment by alexischr** [comment]
@marek-safar @lambdageek  Can I get some input on prioritizing System.Reflection.Emit tasks? For example, ILGenerator.UsingNamespace() and scope mentioned above seems more important to SRE than the public but unused GetSignatureToken override method. Maybe you have some more insights like that?

**Comment by SamMonoRT** [comment]
@steveisok @lambdageek  - this is a really old issue, some of the apis requests have been satisfied in dotnet\runtime repo. Please can one of you take a look and re-assign is necessary or close this.
