### ISSUE TITLE
2019-06 Mono Release

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#15377]
# Products integration

## Visual Studio for Mac

Integrator: @directhex 

Pull Requests:
 - [x] https://github.com/xamarin/md-addins/pull/4758

## Xamarin Designer

Integrator: @directhex 

Pull Requests:
 - [x] https://github.com/xamarin/designer/pull/2078

## Xamarin.Android

Integrator: @steveisok 

Pull Requests:
- [x] https://github.com/xamarin/xamarin-android/pull/3155

## Xamarin.iOS

Integrator: @akoeplinger 

Pull Request:
- [x] https://github.com/xamarin/xamarin-macios/pull/6196

# Releasing Checklist

## Nightly

None

## Preview

Published daily from monthly branch once Visual Studio for Mac has been successfully integrated

- [x] Release notes preview is available on the [website](https://github.com/mono/website/tree/gh-pages/docs/about-mono/releases)

## Stable
Published weekly from the monthly branch once the integration of the products has been completed successfully.

- [x] Publish macOS .pkg and Windows .msi to the download server in the stable channel
- [ ] Publish Linux packages to the package repository in the stable channel
- [x] Update the [Mono Docker](https://github.com/mono/docker) image and send a PR to Docker
- [ ] Publish mkbundle runtime
- [x] Verify tarball exists on the download server
- [x] Remove Preview note from the release notes
- [x] Check a tag for the release exists on GitHub
