### ISSUE TITLE
[netcore] Set up static ALC events

### ISSUE THREAD

**Issue by CoffeeFlux** [mono/mono#16246]
Tests:
- [x] Make System.Tests.AppDomainTests.TypeResolve pass (#18141)
- [x] Make System.Tests.AppDomainTests.ResourceResolve pass (https://github.com/dotnet/runtime/pull/36658)
- [x] Make System.Tests.AppDomainTests.AssemblyLoad pass (#18143)
- [x] Make System.Tests.AppDomainTests.FirstChanceException_Called pass (https://github.com/dotnet/runtime/pull/36658)
- [ ] Make System.Tests.AppDomainTests.AssemblyResolve_FirstChanceException pass (dependent on FirstChanceException)
- [x] Make System.Tests.AppDomainTests.AssemblyResolveInvalidAssemblyName pass (#18157)

Tasks (in flux):
- [x] Copy CoreCLR code into our ALC implementation, marking the region (#16256)
- [x] PR CoreCLR to move the code to shared (https://github.com/dotnet/coreclr/pull/26248)
- [x] Remove our copied implementation (#17767)
- [x] Wire up OnAssemblyResolve (see #15081)
- [x] Wire up OnAssemblyLoad (#18143)
- [ ] Only set RequestingAssembly when appropriate (see https://docs.microsoft.com/en-us/dotnet/api/system.resolveeventargs.requestingassembly?view=netcore-3.0#remarks)
- [x] Wire up OnTypeResolve (#18141)
- [x] Wire up OnResourceResolve (https://github.com/dotnet/runtime/pull/36658)
- [x] Wire up FirstChanceException (https://github.com/dotnet/runtime/pull/36658)
- [x] Remove old MonoDomain Do*Resolve methods and ensure nothing calls them from netcore (#18139, #18141, #18143, https://github.com/dotnet/runtime/pull/36658)

**Comment by CoffeeFlux** [comment]
PRs are out now for the high priority events/tests here. The remaining ones, ResourceResolve and FirstChanceException, are some combination of more difficult/unlikely to be used/unlikely to be fully supported, so I'll get to them later.
