### ISSUE TITLE
[netcore] MicroBenchmarks Performance Bottlenecks

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#16679]
In the past few weeks we made several runs of the [dotnet/performance](https://github.com/dotnet/performance/) microbenchmarks to identify places where Mono is lacking and where performance efforts should be targeted. Some of the issues were resolved by now but others are still pending. This issue aims to track the progress for the problems we discovered. All the performance tests were run with Mono's `--llvm` JIT mode and compared to the numbers of CoreCLR on the same machine.

# High impact

- [x] Slow `Buffer.BlockCopy` (#16678). This affects many low-level string operations.
- [x] Missing caching or optimization for `Activator.CreateInstance<T>` (#16615). Visible in micro benchmarks but likely also affecting common libraries such as JSON.NET which use it for deserialization.
- [ ] Missing caching for reflection methods such as `GetMethod` (#17403)
- [x] Missing intrinsic for Unsafe.InitBlockUnaligned (#16591)
- [x] Buffer.Memmove is slow (#16592)

# Low impact

- [ ] Mono exposes `Vector<T>` as 128-bit, CoreCLR uses 256-bit on hardware that supports it. Implementing 256-bit SIMD support may come with negative consequences though because Mono does not implement most of the `System.Runtime.Intrinsics` namespace and hence the `Vector<T>` code paths are taken more often. Forcing bigger vector sizes could degrade performance for operations where the source operands are smaller than the vector size.

# Unknown impact

- [ ] Slow heap allocations (#16669). This was discovered with the [Burgers_0 microbenchmark](https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/coreclr/Burgers/Burgers.cs#L50-L51). That particular case is obscure use but targeted microbenchmarks show performance disparity. 
- [x] String operations don't implement some [optimized code paths for ASCII only strings](https://github.com/mono/mono/blob/86a0ad2f8885df2795c9d10ee363a6db48998507/netcore/System.Private.CoreLib/shared/System/Globalization/CompareInfo.Unix.cs#L241-L252). This is currently subject to change in CoreCLR and hence non-actionable (https://github.com/dotnet/corefx/issues/40674).
- [ ] `mini_emit_memset`/`mini_emit_memcpy` should use LLVM intrinsics. CoreCLR beats us here by emitting properly vectorized code. (#16716)

**Comment by SamMonoRT** [comment]
@filipnavara - closing this old issue. If you see slower benchmarks running against dotnet\runtime, please open an issue on that repo.
