### ISSUE TITLE
WebAssembly SDK for .NET 5.0

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#16913]
The goal is to have .NET Core SDK targetting WebAssembly, including integration into .NET Core CLI tooling.

## Blockers
- [ ] Resolution on NuGet TFM for new .NET 5.0 SDKs 

## Milestone I
- [ ] Add WASM/Emscripten build targets to CoreFX
- [ ] Build Microsoft.NETCore.App targetting WASM with temporary TFM
- [ ] Integrate Microsoft.NETCore.App NuGet into existing Mono WASM SDK build

## Milestone II
- [ ] Make NuGet package to AOT tooling
- [ ] TBA

**Comment by vargaz** [comment]
To have netcore support in corefx, we need to compile a wasm version of System.Native:
- Need to apply a cleaned up version of this patch:
https://github.com/mono/mono/blob/master/sdks/wasm/netcore-corefx.diff
- Need to compile using this rule:
https://github.com/mono/mono/blob/master/sdks/wasm/Makefile#L209

Note that this requires an emscripten installation on the build bots. Also, the emscripten version should ideally match the emscripten version mono is using, which changes frequently.
