### ISSUE TITLE
2019-08 Mono Release

### ISSUE THREAD

**Issue by steveisok** [mono/mono#17023]
# Products integration

## Visual Studio for Mac

Integrator: @akoeplinger 

Pull Requests:
 - [x] https://github.com/xamarin/md-addins/pull/5134

## Xamarin Designer

Integrator: @akoeplinger 

Pull Requests:
 - [x] https://github.com/xamarin/designer/pull/2263

## Xamarin.Android

Integrator: @steveisok 

Pull Requests:
- [x] https://github.com/xamarin/xamarin-android/pull/3449

## Xamarin.iOS

Integrator: @directhex 

Pull Request:
- [x] https://github.com/xamarin/xamarin-macios/pull/6723

# Releasing Checklist

## Nightly

None

## Preview

Published daily from monthly branch once Visual Studio for Mac has been successfully integrated

- [x] Release notes preview is available on the [website](https://github.com/mono/website/tree/gh-pages/docs/about-mono/releases)

## Stable
Published weekly from the monthly branch once the integration of the products has been completed successfully.

- [x] Publish macOS .pkg and Windows .msi to the download server in the stable channel
- [x] Publish Linux packages to the package repository in the stable channel
- [x] Update the [Mono Docker](https://github.com/mono/docker) image and send a PR to Docker
- [x] Publish mkbundle runtime
- [x] Verify tarball exists on the download server
- [x] Remove Preview note from the release notes and ensure they're complete
- [x] Check a tag for the release exists on GitHub
