### ISSUE TITLE
CoreCLR tests execution on MonoVM

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#17098]
To run all tests locally `cd netcore && make run-tests-coreclr`

## Milestone I
- [ ] Filter-out tests which are CoreCLR VM specific
- [ ] Categorize all failing tests on macOS into following categories
	- [ ] [Mono bugs](https://github.com/mono/mono/labels/epic:%20CoreCLR%20tests?page=3&q=is%3Aopen+label%3A%22epic%3A+CoreCLR+tests%22) -> fill GH issue for each failing group
	- [ ] [Mono missing features](https://github.com/mono/mono/issues/14788) -> create task for each feature
	- [ ] Test bug or limitation -> make CoreCLR PR which fixes the test

## Milestone II
- [ ] Resolve all temporary excluded failing tests
- [ ] Pass CoreFX tests successfully on CI for
	- [ ] macOS - amd64
	- [ ] Linux - amd64
	- [ ] Linux - arm64
	- [ ] Windows - amd64
- [ ] Pass all CoreFX tests in interpreter mode on Mono CI
	- [ ] macOS - amd64
	- [ ] Linux - amd64
	- [ ] Linux - arm64
	- [ ] Windows - amd64

## Milestone III
- [ ] Pass all CoreFX tests in AOT mode on Mono CI
	- [ ] macOS - amd64
	- [ ] Linux - amd64
	- [ ] Windows - amd64

**Comment by SamMonoRT** [comment]
Closing old issue, new tests have been running on dotnet\runtime
