### ISSUE TITLE
Tracking msbuild updates

### ISSUE THREAD

**Issue by radical** [mono/mono#17952]
`2019-08`:
- [x] msbuild PR: https://github.com/mono/msbuild/pull/157
- [x] Bump msbuild+roslyn in mono (https://github.com/mono/mono/pull/17954)
- [x] Bump nuget.exe to 5.4.0, once it becomes available

`2019-10`:
- [x] Bump msbuild in mono (https://github.com/mono/mono/pull/17951)
- [x] Bump nuget.exe to 5.4.0, once it becomes available
- [x] Bump sdks+roslyn (https://github.com/mono/msbuild/pull/163)

`master`:
- [x] Bump msbuild in mono (https://github.com/mono/mono/pull/17950)
- [x] Bump nuget.exe to 5.4.0, once it becomes available
- [x] Bump msbuild+sdks (https://github.com/mono/msbuild/pull/162)

`2019-12`:
- [x] Bump msbuild and roslyn in mono to point to 2019-10 (https://github.com/mono/mono/pull/18046)

`Roslyn`:
- [x] PR: https://github.com/mono/roslyn-binaries/pull/21
- [x] Bump 2019-08 msbuild+mono (https://github.com/mono/mono/pull/17954)
- [x] Bump 2019-10 msbuild+roslyn in mono (https://github.com/mono/mono/pull/18045)
- [x] Bump master msbuild+roslyn in mono (https://github.com/mono/mono/pull/18050)

Branch dependencies:

`mono 2019-08 -> msbuild mono-2019-08 -> { dotnet/toolset 3.1.1xx ; upstream msbuild vs16.4 }`
`mono 2019-10  -> msbuild mono-2019-10 -> { dotnet/toolset 3.1.2xx ; upstream msbuild vs16.5 }`
`mono 2019-12  -> msbuild mono-2019-10 -> { dotnet/toolset 3.1.2xx ; upstream msbuild vs16.5 }`
`mono master    -> msbuild xplat-master -> { dotnet/toolset 3.1.2xx ; upstream msbuild master }`
