### ISSUE TITLE
Epic: ALC-aware embedding APIs

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#18051]
In netcore Mono we will need AssemblyLoadContext-aware embedding APIs.

Currently a lot of APIs take a `MonoDomain*` argument in order to support working with multiple domains.  Many other APIs implicitly work in the "current" domain (internally by calling `mono_domain_get()` to get the active domain of the current thread).

In the netcore configuration, we only have a single domain, but we have multiple assembly load contexts.  These should be consulted when we need to load assemblies or to find types.   It is possible to load the same assembly into multiple ALCs, so an assembly-qualified type name alone is not enough to identify a class uniquely. Currently in the name of expedience many embedding APIs on netcore mono default to the default ALC, so some types that are loaded won't be found.

When looking up a `MonoAssembly*`, `MonoImage*` and `MonoType*` and other metadata, we need to allow embedders to provide an assembly load context.  We also need to be able to query a `MonoAssembly*` to find out which ALC it is loaded in.

To support collectable ALCs (that can be unloaded when no longer in use) we should design new APIs so that if we return an ALC to the embedder, they will need to tell us when they are no longer referencing it.

---

# Phase 0

This is the investigation and deprecation phase.

- [ ] Identify APIs that need an ALC argument - APIs that currently take a `MonoDomain*` or use the current domain but won't consult non-default ALCs for metadata lookup, for example.
- [ ] Mark existing ALC-unaware APIs as deprecated.

# Phase 1

This phase is to make sure we get a good API for working with ALC lifetimes that's compatible with collectability.

- [ ] Add ALC-query APIs for `MonoAssembly*`  (Need to do this in a way that is compatible with collectable ALCs)

# Phase 2

Phase 2 will be to implement the new APIs from Phase 0

- [ ] ...
- [ ] ...

# Future

We may also need:
- To access properties of ALCs.
- To traverse all ALC.
- To create new ALCs.

This can all be done from managed code, so unless a scenario arises where that's not reasonable, we don't need to add these right away.

**Comment by jaykrell** [comment]
Would roughly `typedef MonoDomain MonoAssemblyLoadContext` work?
  Might want separate types.
i.e. pre-netcore are they the same, and netcore is ALC a strict subset of domain?
Partially restated, pre-netcore, is there always exactly one ALC per domain?

Does CoreCLR have an API here already?

Should some/most APIs that use default domain, actually take domain as a parameter?

Is domain implied sometimes by other parameters, e.g. `MonoClass*` or `MonoObject*`?

**Comment by CoffeeFlux** [comment]
> Would roughly typedef MonoDomain MonoAssemblyLoadContext work?
Pretty sure we want separate types. The operations you can perform on a domain are different from an ALC, and even in netcore the root domain still exists and is usable.

> i.e. pre-netcore are they the same, and netcore is ALC a strict subset of domain?
Pre-netcore, ALCs do not exist at all. The argument is just always assume to be NULL.

> Does CoreCLR have an API here already?
They have no embedding API, no. We're just modifying ours.

> Should some/most APIs that use default domain, actually take domain as a parameter?
This is a little more complicated. If we're just going wild with deprecations then no, I don't think there's any point on netcore since there's only ever one, but others may disagree. However, I'm not sure it's worth breaking a ton of functions that take a MonoDomain argument just to remove said argument.

> Is domain implied sometimes by other parameters, e.g. MonoClass* or MonoObject*?
It's implied by ALCs directly and I think MonoClass highly indirectly, maybe even mandating a lookup? Since it has a MonoImage field, which in turn corresponds to a MonoAssembly, which you can look up the domain for?
