### ISSUE TITLE
2019-12 Mono Release

### ISSUE THREAD

**Issue by steveisok** [mono/mono#18123]
# Products integration

## Visual Studio for Mac

Integrator: @radical

Pull Requests:
 - [X] ~https://github.com/xamarin/md-addins/pull/6037~ superseded by https://github.com/xamarin/vsmac/pull/150

## Xamarin Designer

Integrator: @radical  

Pull Requests:
 - [X] https://github.com/xamarin/designer/pull/2591

## Xamarin.Android

Integrator: @BrzVlad  

Pull Requests:
- [X] https://github.com/xamarin/xamarin-android/pull/3981

## Xamarin.iOS

Integrator: @SamMonoRT  

Pull Request:
- [X] https://github.com/xamarin/xamarin-macios/pull/7537

# Releasing Checklist

## Nightly

None

## Preview

Published daily from monthly branch once Visual Studio for Mac has been successfully integrated

- [] Release notes preview is available on the [website](https://github.com/mono/website/tree/gh-pages/docs/about-mono/releases)

## Stable
Published weekly from the monthly branch once the integration of the products has been completed successfully.

- [ ] Publish macOS .pkg and Windows .msi to the download server in the stable channel
- [ ] Publish Linux packages to the package repository in the stable channel
- [ ] Update the [Mono Docker](https://github.com/mono/docker) image and send a PR to Docker
- [ ] Publish mkbundle runtime
- [ ] Verify tarball exists on the download server
- [ ] Remove Preview note from the release notes and ensure they're complete
- [ ] Check a tag for the release exists on GitHub

**Comment by SamMonoRT** [comment]
@steveisok - do we need this open ?

**Comment by akoeplinger** [comment]
We haven't done any of the checklist items, 2019-12 release notes are missing etc.
Btw. is there an issue for the 2020-02 release?
