### ISSUE TITLE
[loader] Mono startup stats tracking

### ISSUE THREAD

**Issue by CoffeeFlux** [mono/mono#18754]
Our winter externs worked to extend the `--stats` command to take a method name and dump the existing counters before it is run. This exists in Mono master on Android, OSX, and Linux, with the JIT and interpreter, but the following potential work remains:

- [ ] Make the system statistics work on Windows
- [ ] Make the system statistics work on wasm
- [ ] Check if the system statistics work on iOS and, if necessary, make them functional
- [ ] Add a callback to the Mono API to report the stats in a more useful vehicle than stdout
- [ ] Add support for stat dumping with AOT
- [ ] Investigate moving `mono_stats` and `mono_jit_stats` into the existing counters API

**Comment by grendello** [comment]
These might be outside the scope for this issue, but won't hurt to list them

- [ ] Make it possible to filter the data by namespace, class (akin to `--trace` which supports it, it would be nice if we could do it via an API)
- [ ] Take advantage of Linux perf capabilities a'la [SimplePerf](https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/README.md)

**Comment by lambdageek** [comment]
>  Make it possible to filter the data by namespace, class (akin to `--trace` which supports it, it would be nice if we could do it via an API)

Not totally clear on what's being asked for.  Are you asking for the ability to make some of the counters only fire for some classes and not for others? (for example: count only the number of jitted methods from the `System` namespace)

**Comment by grendello** [comment]
@lambdageek yep, exactly that. From the mono manpage for `--trace`:

```
--trace[=expression]
              Shows method names as they are invoked.  By default all methods are traced.  The trace can be customized to include or exclude methods, classes or assemblies.  A trace expression is a comma separated list of targets, each target can be prefixed with a minus sign to turn off a  particular  tar‐
              get.   The  words  `program',  `all'  and `disabled' have special meaning.  `program' refers to the main program being executed, and `all' means all the method calls.  The `disabled' option is used to start up with tracing disabled.  It can be enabled at a later point in time in the program by
              sending the SIGUSR2 signal to the runtime.  Assemblies are specified by their name, for example, to trace all calls in the System assembly, use:

                   mono --trace=System app.exe

              Classes are specified with the T: prefix.  For example, to trace all calls to the System.String class, use:

                   mono --trace=T:System.String app.exe

              And individual methods are referenced with the M: prefix, and the standard method notation:

                   mono --trace=M:System.Console:WriteLine app.exe

              Exceptions can also be traced, it will cause a stack trace to be printed every time an exception of the specified type is thrown.  The exception type can be specified with or without the namespace, and to trace all exceptions, specify 'all' as the type name.

                   mono --trace=E:System.Exception app.exe

              As previously noted, various rules can be specified at once:

                   mono --trace=T:System.String,T:System.Random app.exe

              You can exclude pieces, the next example traces calls to System.String except for the System.String:Concat method.

                   mono --trace=T:System.String,-M:System.String:Concat

              You can trace managed to unmanaged transitions using the wrapper qualifier:

                   mono --trace=wrapper app.exe

              Finally, namespaces can be specified using the N: prefix:

                   mono --trace=N:System.Xml
```
