### ISSUE TITLE
[wasm][debugger] Tracking issue for TODOs

### ISSUE THREAD

**Issue by radical** [mono/mono#19800]
# Visualization for locals/properties

- [ ] Surface exceptions thrown during a getter invocation
- [ ] ref/out vars
- [ ] multi-dim arrays, should show up as `int [2, 4]`, and details as `[0, 0], [0, 1]..`
- [ ] Arrays show a `length` property in vscode, remove that?
- [ ] Private/internal fields/properties
- [ ] Allow default getters for `Nullable`?

# Others
- [ ] VS like async stacktrace
- [ ] Getters on valuetypes
- [ ] Move tests to puppeteersharp
- [ ] Move test setup/teardown code to .ctor and IDispose (or xunit's equivalent)
