### ISSUE TITLE
2018-02 Products Integration

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6842]
### VSfM

Integrator: @kg

Pull Requests:
 - [x] https://github.com/mono/monodevelop/pull/3836
 - [x] https://github.com/xamarin/md-addins/pull/2884

Wrench:
 - https://wrench.internalx.com/Wrench/index.aspx?lane=monodevelop-lion-mono-2018-02

### XA

Integrator: @baulig

Pull Requests:
 - [x] https://github.com/xamarin/xamarin-android/pull/1289
 - [x] https://github.com/xamarin/monodroid/pull/746

Wrench:
 - https://wrench.internalx.com/Wrench/index.aspx?lane=monodroid-mavericks-mono-2018-02
   - https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=5930&host_id=163&revision_id=932473

VSTS (QA):
 - https://devdiv.visualstudio.com/DevDiv/Xamarin%20QA/_workitems/edit/587352

### XI

Integrator: @lewurm

Pull Request:
 - [x] https://github.com/xamarin/xamarin-macios/pull/3402

Wrench:
 - https://wrench.internalx.com/Wrench/index.aspx?lane=macios-mac-mono-2018-02
   - https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=5929&host_id=392&revision_id=932470

VSTS (QA):
 - https://devdiv.visualstudio.com/DevDiv/Xamarin%20QA/_workitems/edit/587386
   - https://devdiv.visualstudio.com/DevDiv/_release?definitionId=708&releaseId=86899&_a=release-summary
   - https://devdiv.visualstudio.com/DevDiv/_release?definitionId=709&releaseId=86937&_a=release-summary
