### ISSUE TITLE
Epic 7: C#7 support for mcs

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6854]
## C# 7.0
- [ ] Pattern matching
- [ ] Tuples
- [ ] Tuples Deconstruction
- [ ] Discards
- [ ] Local Functions
- [ ] Binary Literals
- [ ] Digit Separators
- [ ] Generalized async return types
- [ ] More expression-bodied members
- [ ] Throw expressions

## C# 7.1
- [ ] Async main
- [ ] Default literal expressions
- [ ] Reference assemblies
- [ ] Inferred tuple element names
- [ ] Pattern-matching with generics

## C# 7.2

- [ ] ref struct
- [ ] non-trailing named arguments
- [ ] private protected
- [ ] conditional ref operator
- [ ] leading digit separator
- [ ] readonly struct
