### ISSUE TITLE
Epic: IL Interpreter

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6860]
IL Interpreter can be used on target platforms that cannot fully support the JIT (ex: iOS), and the one with even more limitations (ex: watchOS only supports bitcode) to handle the .NET APIs which depends on the JIT. It will also help in our future effort to port to new platforms (ex: webassembly) where it's much easier to port than the JIT.

Integration to other components and features of the runtime will be needed: debugger, AOT with mixed-mode execution, etc.

iOS is the platform that will most benefit from this effort because it currently doesn't support multiple features that are impossible to support with fullAOT and without a JIT. For example, `System.Reflection.Emit` is currently disabled for lack of an interpreter, and `dynamics` use a C# interpreter that is slow and doesn't support all features.

## Milestone I

- [x] Make the interpreter pass all runtime tests #6861 
- [x] Make the interpreter pass all BCL tests #7053
- [x] Update XI build targets to propagate interpreter settings #6916 
- [x] Build interpreter library #6918
- [x] Add support for icall linking #6808 

## Milestone II
- [x] Support Interpreter in mixed-mode (AOT fallback mode) #6915
- [x] Enable SRE for profiles which support the interpreter
- [x] Make managed BCL interpreter implementation optional (SLE parts)
- [x] Make the fullAOT+interp pass all BCL tests #11566 
- [x] Make the fullAOT+interp pass all runtime tests #11567 
- [x] Implement easy optimizations with noticeable impact #11531

## Future
- [ ] Generate icall table from the managed linker #6809

**Comment by BrzVlad** [comment]
Closed as per comment from https://github.com/mono/mono/issues/6809
