### ISSUE TITLE
Make the interpreter pass all runtime tests

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6861]
We want to pass on ARM, ARM64, amd64 platforms

## ARM

- [x] appdomain-unload-callback.exe
- [x] appdomain-unload.exe
- [x] array_load_exception.exe
- [ ] assemblyresolve_event6.exe
- [ ] async-with-cb-throws.exe
- [ ] block_guard_restore_aligment_on_exit.exe
- [ ] bug-323114.exe
- [ ] bug-335131.2.exe
- [ ] bug-415577.exe
- [ ] bug-45841-fpstack-exceptions.exe
- [ ] bug-48015.exe
- [x] bug-58782-capture-and-throw.exe
- [x] bug-58782-plain-throw.exe
- [ ] bug-60862.exe
- [ ] bug-80307.exe
- [ ] bug-80392.2.exe
- [ ] bug445361.exe
- [ ] calliGenericTest.exe
- [ ] cominterop.exe
- [ ] context-static.exe
- [ ] delegate-async-exit.exe
- [ ] delegate-delegate-exit.exe
- [ ] delegate-exit.exe
- [x] delegate-with-null-target.exe
- [ ] delegate1.exe
- [ ] delegate3.exe
- [ ] delegate5.exe
- [ ] delegate8.exe
- [ ] delegate9.exe
- [ ] dim-diamondshape.exe
- [ ] dynamic-method-stack-traces.exe
- [ ] even-odd.exe
- [ ] exception18.exe
- [ ] field-access.exe
- [ ] finalizer-exception.exe
- [x] finalizer-thread.exe
- [ ] handleref.exe
- [ ] itail1.exe
- [ ] monitor-abort.exe
- [ ] nullable_boxing.2.exe
- [ ] pinvoke.exe
- [ ] pinvoke2.exe
- [ ] pinvoke3.exe
- [ ] remoting2.exe
- [ ] remoting3.exe
- [ ] safehandle.2.exe
- [ ] sitail1.exe
- [ ] stackframes-async.2.exe
- [ ] static-constructor.exe
- [ ] threadpool-exceptions2.exe
- [ ] threadpool-exceptions3.exe
- [ ] threadpool-exceptions4.exe
- [ ] threadpool-exceptions5.exe
- [ ] threadpool-exceptions6.exe
- [ ] thunks.exe
- [x] thread6.exe
- [ ] typeload-unaligned.exe
- [ ] vararg.exe
- [ ] vararg2.exe
- [ ] vararg3.exe

## ARM64

- [x] array_load_exception.exe
- [x] bug-335131.2.exe
- [ ] bug-48015.exe
- [x] bug-58782-capture-and-throw.exe
- [x] bug-58782-plain-throw.exe
- [x] calliGenericTest.exe
- [x] classinit3.exe
- [x] delegate-with-null-target.exe
- [ ] dim-diamondshape.exe
- [ ] itail1.exe
- [x] pinvoke2.exe
- [ ] pinvoke3.exe
- [ ] sitail1.exe
- [x] test-tls.exe
- [x] thread6.exe
- [x] vararg.exe
- [x] vararg2.exe
- [x] vararg3.exe

## x64

- [ ] assemblyresolve_event6.exe
- [ ] bug-48015.exe
- [ ] bug-60862.exe
- [x] calliGenericTest.exe
- [ ] cominterop.exe
- [x] delegate-with-null-target.exe
- [ ] dim-diamondshape.exe
- [ ] itail1.exe
- [x] pinvoke.exe
- [x] pinvoke2.exe
- [ ] pinvoke3.exe
- [ ] sitail1.exe

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/7128

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/6930

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/6917

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/6868

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/6853

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/6852

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/7057

**Comment by luhenry** [comment]
There are still a lot of tests disabled on ARM due to a bug with register R8 clobbering on trampolines

**Comment by luhenry** [comment]
The `pinvoke` tests are going to be harder: we need to allow for restoring context into a interpreter frame. Right now this is guarded against by an assertion, so we need to relax and fix that.
