### ISSUE TITLE
Epic: SDKs support

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6862]
The Mono `sdks/` folder contains tooling and configuration for building Mono for different embedders. Right now it's WebAssembly, iOS and Android. By having this setup we'd like to achieve following.

### Xamarin Embedders
They should be able to consume Mono without caring how it's built and what dependencies it has. They should be able to drive source and binary builds using the same bootstrapping code by simply changing a flag. The build scripts interface should be minimal, stable and tested.

### Mono Developers
They should be able to work on our day-to-day targets with ease. The SDKs should drive productivity in the form of easier on-boarding/setup, faster build times and streamlined provisioning/deployment/debugging/testing. It should be very opinionated and consistent to facilitate our communication.

## Milestone I
- [x] Mono SDK side support for Android https://github.com/mono/mono/issues/6889
- [x] Mono SDK side support for iOS #7063

## Milestone II
- [x] Introduce CI lane with Mono iOS SDK running on a device #7030
- [x] Introduce CI lane with Mono Android SDK running on a device #7031 

## Milestone III
- [x] Move XI/XA BCL specific implementation to Mono source tree #7192
- [x] Include BCL tests (nunit and xunit) as part of the package #10900
- [ ] Execute BCL xunit tests in SDKs test run #9338
- [x] Add cross compilers support for iOS and Android
- [x] Upload and Download packages of MXE, LLVM

## Milestone IV
- [ ] Development configuration improvements #10376

## Future
- [ ] Include SDKs as part of Mono packages/installer

**Comment by filipnavara** [comment]
Is there any particular reason why Xamarin.Mac is not on the list as well? It would probably be very similar to the XI.

**Comment by ArionTT** [comment]
The sdks is just a test. If I want to run it on my android device, what preparation should I do？

I want to rewrite it to build a android application to call C# assembly in Java code or NDK C++ code just like unity done.
