### ISSUE TITLE
Support Interpreter in mixed-mode

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6915]
## General

By mixed mode we mean that some oracle can decide if a method should be executed by the JIT (/AOT runtime) or interpreter. The default oracle is: If a method is available as AOT'd method, execute this, otherwise fall back to the interpreter. Example: On iOS we cannot JIT, therefore we have FullAOT. It can't handle `System.Reflection.Emit` (SRE) though, so those methods will be executed by the interpreter.

### AOT Oracle

The current supported mode works like this:
1. AOT compile assemblies with `--aot=full,interp`
2. execute runtime with `--full-aot --interp`

Currently, this isn't tested very well.

### Hardcoded Oracle

We can force the interpreter with `--interp=interp-only=SomeClassName` for a specific class, or force the JIT with `--interp=jit=SomeClassName` the other way around. This is used by the mixed mode regression test:
https://github.com/mono/mono/blob/42dd7d3e84b3bde4428c0e410e7e56c62db40ce3/mono/mini/Makefile.am.in#L770-L771

We should extend this mode so that we can for example specify namespaces.

### Hash Oracle

In order to stress test the mixed mode transitions, we should have a mode that decides seemingly randomly, but in a deterministic fashion. This can be achieved by using a hash-function for a method and a seed, for example:

```C
gboolean use_interp = (hash(method) ^ seed) / (double)INT_MAX > 0.5
```

## Plan for testing

- [ ] JIT (BCL) + interp with extended hardcoded oracle
- [ ] JIT + interp with hash oracle. Not sure yet if this will be suitable for CI, but definitely useful for stress testing locally.
- [ ] FullAOT (BCL) + interp with with default oracle
- [ ] FullAOT+LLVM (BCL) + interp with default oracle

**Comment by vargaz** [comment]
This is now implemented, using full-aot+interpreter fallback, i.e. full-aot everything, then run
using mono --full-aot --interp.

**Comment by lewurm** [comment]
we should add a CI lane for it

**Comment by vargaz** [comment]
Since the interpreter is only a fallback, its not very easy to test in general, since all methods are already aot-ed. I tested it by running mixed.exe with:
--full-aot --interp=interp-only=InterpClass mixed.exe

**Comment by luhenry** [comment]
@vargaz if you only AOT the BCL (and not the test suite), do you think we would test enough of mixed-mode?

**Comment by marek-safar** [comment]
I don't see a reason for a new CI line. This can be easily tested on interpreter lane.

@vargaz could you write an explicit test for this. For example, using cil-string or SRE?

**Comment by lewurm** [comment]
The "AOT Oracle" works:
* Our iOS SDK CI lane added some testing a while ago: https://github.com/mono/mono/pull/9493
* Xamarin.iOS supports this mixed mode as well: https://github.com/xamarin/xamarin-macios/pull/4751 and works for the `monotouch-tests` https://github.com/xamarin/xamarin-macios/pull/5051
* Vlad recently added a BCL profile so we can test this mode better on our CI: https://github.com/mono/mono/pull/11553 let's keep track of the status in this issue: https://github.com/mono/mono/issues/11566 and https://github.com/mono/mono/issues/11567.

As for the "Hash Oracle", I think it would be a nice-to-have feature, but it isn't blocking anything, so I opened another issue to track the status there: https://github.com/mono/mono/issues/11568.

I think this issue can be closed 🎉
