### ISSUE TITLE
Hybrid Suspend

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6921]
# Goal

As a way to reduce the risk of bing-bang change, we are approaching the project of transitioning to cooperative suspend by a middle ground approach: hybrid suspend. It consist in using cooperative suspend for runtime and managed code, and preemptive suspend for any other kind of code (external libraries, OS, etc.). Thus, preemptive suspend is used only for code which is not controlled by Mono, while cooperative suspend is only used for code which is fully controlled by Mono. This forces us to make sure we transition to the right state, to ensure we use the proper mechanism of suspending.

A _hopefully_ exhaustive list of where these transitions are needed is:
 1. managed-to-native wrappers
 2. native-to-managed wrappers
 3. MONO_API functions
 4. trampolines
 5. external libraries calls (libc, btls, etc.)

Points 1. and 2. are quite easy to achieve, and are already working for supporting cooperative suspend on watchOS. Some of 3., 4. and 5. have already been done for watchOS and Mono's CI for cooperative suspend. Unfortunately, 3. and 4. are not complete enough to fully support VSfM, XI/XM and XA, or any other embedding project.

We want to switch to hybrid suspend by default by `2018-08`, and to do so we have identified some necessary steps to ship, and some longer-term improvement steps.

# Tasks

## For `2018-08`

 - [x] Implement hybrid suspend (native -> preemptive; runtime+managed -> cooperative) - #8068
 - [x] `MONO_API` functions and trampolines
   - List functions loaded from XI/XM and XA, and functions which are public API: https://gist.github.com/luhenry/f450d55128deddcedc2e27852ab6dc23 /cc @luhenry
   - Ensure transition in the above functions and trampolines
 - [ ] Performance: measure impact of hybrid suspend + fix major regressions
   - Some possible measurements
     - time-to-suspend
     - wall clock time: benchmarks, VSfM (startup time, new projects, new file, etc.)
 - [x] Documentation: how to disable, what's needed to transition embedders, how to use diagnostics
 - [ ] Timeout time-to-suspend on CI
 - [x] Diagnostics: `mono_trace` in `mono-threads-debug.h`
 - [ ] Resolve failing tests
   - [x] `abort-cctor.exe` #7599 
   - [x] `bug-58782-plain-throw.exe` and `bug-58782-capture-and-throw.exe` #5837
   - [ ] https://github.com/mono/mono/issues/7981 - Sporadic `MonoTests.System.Runtime.Remoting.RemotingServicesTest.Bug46473` BLOCKING to BLOCKING transition (new issue created from comments below)
    - [x] Sporadic `bug-18026.exe` timeouts - https://github.com/mono/mono/issues/6921#issuecomment-384774625 - fixed by #9347 
   - [ ] System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest8_Values_NegativeCases failure
   - [x] Fix `Mono.Profiler.Log-xunit` tests - #8355  
   - [x] `marshal_mutex` deadlock - #9407 - fixed in #9408 
   - [ ] Make `mono_threads_enter_gc_safe_region_unbalanced_with_info` cheaper on normal platforms #9414
   - [x] Turn it on by default on desktop #9811

## For `Future`

 - [ ] Static analysis:  Centrinel checks for missing transitions in `MONO_API` functions;
   - Centrinel checks to insert `MONO_REQ_GC_UNSAFE_MODE` assertions in functions that touch managed memory.
 - [ ] Diagnostics:
   - [x] Fix BLOCKING -> RUNNING transitions to do no locking - #8356 
   - [ ] Integrate with verbose crashes feature
 - [ ] `MONO_API` functions:
   - All other `MONO_API` functions not loaded by XI/XM/XA
 - [ ] Performance: fix tail of regressions
 - [ ] Documentation: how does it work

# Documentation

https://paper.dropbox.com/doc/What-I-know-about-suspend-GtXdT1CxuMsqwSBFVLqQf

**Comment by luhenry** [comment]
https://github.com/mono/mono/pull/7046

**Comment by alexischr** [comment]
Observed in https://jenkins.mono-project.com/job/test-mono-pull-request-coop/2298/parsed_console/log.html: 

```
***** MonoTests.System.Runtime.Remoting.RemotingServicesTest.Bug46473
Assertion failure in thread 0x7f21a504b740 due to: Cannot transition thread 0x7f21a504b740 from STATE_BLOCKING with DO_BLOCKING
Last 3 state transitions: (most recent first)
[DO_BLOCKING] RUNNING -> STATE_BLOCKING (0) 0 at:
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ef31a) [0x560336a6f31a]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eb477) [0x560336a6b477]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ec7a2) [0x560336a6c7a2]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ec7e6) [0x560336a6c7e6]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x23e367) [0x5603369be367]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x23f59f) [0x5603369bf59f]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2786f0) [0x5603369f86f0]
[DONE_BLOCKING] STATE_BLOCKING -> RUNNING (0) 0 at:
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ef31a) [0x560336a6f31a]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eb5a9) [0x560336a6b5a9]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(mono_threads_exit_gc_safe_region_unbalanced+0x1f) [0x560336a6c86f]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x186407) [0x560336906407]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x28c161) [0x560336a0c161]
	at [0x41deb3c5]
[DO_BLOCKING] RUNNING -> STATE_BLOCKING (0) 0 at:
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ef31a) [0x560336a6f31a]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eb477) [0x560336a6b477]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ec7a2) [0x560336a6c7a2]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ec7e6) [0x560336a6c7e6]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x1863e3) [0x5603369063e3]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x28c161) [0x560336a0c161]
	at [0x41deb3c5]

Stacktrace:

  at <unknown> <0xffffffff>
```

**Comment by luhenry** [comment]
The experimentation to get state transitions at `MONO_API` surface (gc unsafe for runtime+managed, gc safe for external) is quite conclusive for VSfM. 

@lambdageek will start working on the hybrid suspend (coop for runtime+managed, async for external) this week.

**Comment by lambdageek** [comment]
Got another instance of  https://github.com/mono/mono/issues/6921#issuecomment-377394471 at https://github.com/mono/mono/pull/7887 https://jenkins.mono-project.com/job/test-mono-pull-request-coop/2391/parsed_console/log.html

```
***** MonoTests.System.Runtime.Remoting.RemotingServicesTest.Bug46473
Stacktrace:

  at <unknown> <0xffffffff>
Assertion failure in thread 0x7f88e477a740 due to: Cannot transition thread 0x7f88e477a740 from STATE_BLOCKING with DO_BLOCKING
Last 3 state transitions: (most recent first)
[DO_BLOCKING] RUNNING -> STATE_BLOCKING (0) 0 at:
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ef5fa) [0x5614a691f5fa]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eb757) [0x5614a691b757]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eca82) [0x5614a691ca82]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ecac6) [0x5614a691cac6]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x23e647) [0x5614a686e647]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x23f87f) [0x5614a686f87f]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2789d0) [0x5614a68a89d0]
[DONE_BLOCKING] STATE_BLOCKING -> RUNNING (0) 0 at:
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ef5fa) [0x5614a691f5fa]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eb889) [0x5614a691b889]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(mono_threads_exit_gc_safe_region_unbalanced+0x1f) [0x5614a691cb4f]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x1d3c8f) [0x5614a6803c8f]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x1a5832) [0x5614a67d5832]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(mono_class_get_checked+0x105) [0x5614a67d15e5]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0xba72c) [0x5614a66ea72c]
[DO_BLOCKING] RUNNING -> STATE_BLOCKING (0) 0 at:
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ef5fa) [0x5614a691f5fa]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eb757) [0x5614a691b757]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2eca82) [0x5614a691ca82]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x2ecac6) [0x5614a691cac6]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x1d3c6f) [0x5614a6803c6f]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(+0x1a5832) [0x5614a67d5832]
	at /mnt/jenkins/workspace/test-mono-pull-request-coop/mono/mini/mono(mono_class_get_checked+0x105) [0x5614a67d15e5]
```

**Comment by lambdageek** [comment]
Seen on the i386 coop jenkins job for #7887 https://jenkins.mono-project.com/job/test-mono-pull-request-coop-i386/2378/parsed_console/log.html

```
System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest8_Values_NegativeCases [FAIL]
      RunThreadLocalTest8_Values: Expected thread local to release the object and for it to be finalized
      Expected: True
      Actual:   False
      Stack Trace:
          at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in /mnt/jenkins/workspace/test-mono-pull-request-coop-i386/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
  Finished:    net_4_x_corlib_xunit-test
```

**Comment by luhenry** [comment]
Since Cooperative Suspend will require changes to the embedding API, we are working on getting Hybrid Suspend enabled by default (instead of the full cooperative suspend) as it can do without this major constraint.

**Comment by lambdageek** [comment]
Sporadic timeouts on `bug-18026.exe` on the Linux x64 Hybrid Suspend lane.

Wanted: better error output with a full gdb backtrace.

```
bug-18026.exe
=============== bug-18026.exe.stdout ===============
[New LWP 27522]
[New LWP 27523]
[New LWP 27525]
[New LWP 27526]
[New LWP 27528]
[New LWP 27529]
[New LWP 27531]
[New LWP 27534]
[New LWP 27535]
[New LWP 27536]
[New LWP 27537]
[New LWP 27538]
[New LWP 27539]
[New LWP 27570]
[New LWP 27572]
[New LWP 27575]
[New LWP 27576]
[New LWP 27577]
[New LWP 27579]
[New LWP 27581]
[New LWP 27585]
[New LWP 27586]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  Id   Target Id         Frame 
* 1    Thread 0x7fa25945b740 (LWP 27501) "mono" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  2    Thread 0x7fa257bff700 (LWP 27522) "SGen worker" 0x00007fa25892615f in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
  3    Thread 0x7fa258362700 (LWP 27523) "Finalizer" 0x00007fa258928536 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
  4    Thread 0x7fa2555a6700 (LWP 27525) "mono" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  5    Thread 0x7fa2553a5700 (LWP 27526) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  6    Thread 0x7fa2551a4700 (LWP 27528) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  7    Thread 0x7fa254fa3700 (LWP 27529) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  8    Thread 0x7fa254da2700 (LWP 27531) "Thread Pool Wor" 0x00007fa258928536 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
  9    Thread 0x7fa254ba1700 (LWP 27534) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  10   Thread 0x7fa2549a0700 (LWP 27535) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  11   Thread 0x7fa25479f700 (LWP 27536) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  12   Thread 0x7fa25459e700 (LWP 27537) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  13   Thread 0x7fa25439d700 (LWP 27538) "Thread Pool Wor" 0x00007fa258928536 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
  14   Thread 0x7fa227fff700 (LWP 27539) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  15   Thread 0x7fa227dfe700 (LWP 27570) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  16   Thread 0x7fa227bfd700 (LWP 27572) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  17   Thread 0x7fa2279fc700 (LWP 27575) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  18   Thread 0x7fa2277fb700 (LWP 27576) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  19   Thread 0x7fa2275fa700 (LWP 27577) "Thread Pool Wor" 0x00007fa25845828b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
  20   Thread 0x7fa2273f9700 (LWP 27579) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  21   Thread 0x7fa2271f8700 (LWP 27581) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  22   Thread 0x7fa226ff7700 (LWP 27585) "Thread Pool Wor" 0x00007fa2583963d6 in sigsuspend () from /lib/x86_64-linux-gnu/libc.so.6
  23   Thread 0x7fa226df6700 (LWP 27586) "Thread Pool Wor" 0x00007fa258928536 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0

Thread 23 (Thread 0x7fa226df6700 (LWP 27586)):
$1 = void

Thread 22 (Thread 0x7fa226ff7700 (LWP 27585)):

"<threadpool thread>" tid=0x7fa226ff7700 this=0x7fa2593af1e0 , thread handle : 0x7fa220001a20, state : not waiting

$2 = void

Thread 21 (Thread 0x7fa2271f8700 (LWP 27581)):

"Thread Pool Worker" tid=0x7fa2271f8700 this=0x7fa2593aee08 , thread handle : 0x7fa218001a20, state : not waiting

$3 = void

Thread 20 (Thread 0x7fa2273f9700 (LWP 27579)):

"Thread Pool Worker" tid=0x7fa2273f9700 this=0x7fa2593ae7a0 , thread handle : 0x7fa21c001a20, state : not waiting

$4 = void

Thread 19 (Thread 0x7fa2275fa700 (LWP 27577)):

=============== EOF ===============
=============== bug-18026.exe.stderr ===============

=============== EOF ===============
```

**Comment by luhenry** [comment]
List of symbols used by XI/XM/XA/VSfM: https://gist.github.com/luhenry/f450d55128deddcedc2e27852ab6dc23

**Comment by lambdageek** [comment]
I think https://github.com/mono/mono/issues/6921#issuecomment-384774625 will be fixed by #9347

**Comment by lambdageek** [comment]
This work has been completed for a few years.  It is in mono 6.12 (2020-02) and in .NET 5+ on platforms where Mono is used
