### ISSUE TITLE
Epic: MonoClass refactoring

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6924]
There are problems with lazy initialisation and accessing fields of MonoClass. We should also use this as the way to move to MonoType at more places.

## Milestone I
- [ ] Extract the getter/setter + assertion + leveled init for MonoClass
- [ ] Add tests for MonoClass initialization
- [ ] MonoType refactoring

## Milestone II
- [ ] Loader refactoring
- [ ] Generic sharing refactoring
