### ISSUE TITLE
Epic: Default Interface Implementation

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6961]
C#/.NET needs default interface method (**dim**) support. A lack of default interface is our major API binding problems in Java and iOS (swift/objc).

C#8 release should include [default interface methods](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md)

C# Feature [specification](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md)

IL specification [draft](https://microsoft-my.sharepoint.com/personal/michals_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7Bda3281cc-ebc0-4312-9f14-c87acc2caab5%7D&action=edit&slrid=5307439e-70e9-0000-6544-5ca8fea3e975)

## Milestone I

- [x] Port coreclr dim tests to Mono 
- [ ] Improve runtime support for dim to pass all tests
- [ ] Bundle custom built of csc with dim support

## Milestone II

- [ ] Run Roslyn dim tests as part of acceptance tests
- [ ] Switch to official build of Roslyn with dim support
