### ISSUE TITLE
Epic: Roslyn tests

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#6991]
We need to resolve bugs and tests problems in all Roslyn unit tests assemblies as they are important for us to run.

## Milestone I
- [x] Roslyn.Compilers.CSharp.Syntax.UnitTests
- [ ] Roslyn.Compilers.CSharp.Semantic.UnitTests
- [ ] Roslyn.Compilers.CSharp.Symbol.UnitTests
- [ ] Roslyn.Compilers.CSharp.Emit.UnitTests
- [ ] Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests

The list comes from 
https://github.com/mono/roslyn/blob/mono-testing/mono-testing.sh

## Milestone II

There are additional tests we could run as well as we need to figure out how keep the tests repo synchronized with bundled csc we test against

**Comment by jaredpar** [comment]
> https://github.com/mono/roslyn/blob/mono-testing/mono-testing.sh

Why have a custom script here versus using `./build.sh --test --mono`. The latter will run the tests as we're expecting using mono from the command line. 

The script in the current form will get broken from time to time as our build layout and TFs change. It's already broken if you sync up with dotnet/master as our tests changed from net461 to net46 and all of our test assemblies got renamed. 

What problems are you all having getting MS.CS.Symbols.UnitTests running? Those should have worked on Mono for some time now.

**Comment by jaredpar** [comment]
Here is the issue we are tracking on our side to do this work. 

https://github.com/dotnet/roslyn/issues/28011

**Comment by marek-safar** [comment]
@jaredpar I am happy to switch to `./build.sh --test --mono` if it does the same thing but it was not working as expected when we played with it.

Last time we ran `Roslyn.Compilers.CSharp.Semantic.UnitTests.dll` we had about 59 failures but don't have that list at hand but we are going to re-run it next week.

**Comment by jaredpar** [comment]
@marek-safar 

> I am happy to switch to ./build.sh --test --mono if it does the same thing but it was not working as expected when we played with it.

This is what we've been investing in. If you hit issues with it, or it's not meeting your needs, please let us know and we can work it out. 

The intent with that switch is to essentially "run all test using the `mono` available on `$PATH`". Our CI is slightly different in that it creates [a docker container](https://github.com/dotnet/roslyn/blob/master/build/scripts/docker/Dockerfile), installs the latest stable mono package and then runs tests. 

> Last time we ran Roslyn.Compilers.CSharp.Semantic.UnitTests.dll we had about 59 failures but don't have that list at hand but we are going to re-run it next week.

Do you have a list of the failures? I've never been able to get it to complete a run without having a crash in Mono. If I knew the tests that were failing I could probably work out what is going on and address them. 

Now that our C# tests run on Linux CoreClr I would expect there to be a pretty small number failing in Mono. 59 is a bit higher than I'd expect but possibly there is just a single choke point that is causing a problem. When is the last time you ran them?
