### ISSUE TITLE
Make the interpreter pass all BCL tests

### ISSUE THREAD

**Issue by luhenry** [mono/mono#7053]
We want the interpreter to be on par with the JIT in regards to the BCL test suite. As we don't have support for running tests in parallel we should add them in the following order.

For all assemblies include both add xunit and nunit versions.

- [x] mscorlib
- [x] mscorlib / xunit
- [x] Mono.Debugger.Soft
- [x] Mono.Profiler.Log
- [x] System.Core
- [x] System.Core / xunit
- [x] System.Xml
- [x] System.Numerics
- [x] System.Numerics / xunit
- [x] Microsoft.CSharp
- [ ] Microsoft.CSharp / xunit
- [x] System.Security
- [ ] System.Security / xunit
- [x] System
- [x] System / xunit
- [x] System.Data
- [x] System.Data / xunit

**Comment by luhenry** [comment]
We could have a lane, but there are still around 50 tests that are failing. We should disable these tests for now, and fix them as we go.

**Comment by marek-safar** [comment]
We should focus on core (mobile) assemblies only

**Comment by luhenry** [comment]
Only very few assemblies left after https://github.com/mono/mono/pull/9648

**Comment by lewurm** [comment]
https://github.com/mono/mono/pull/10095 added `System.Core / xunit`.

@BrzVlad do you remember what's the issue with `Microsoft.CSharp / xunit`?

**Comment by BrzVlad** [comment]
@lewurm I don't remember. I stressed  it for some time with a recent mono on amd64 and it it passed all the time. Maybe we should enable it.
