### ISSUE TITLE
Epic: Client Certificate Support

### ISSUE THREAD

**Issue by baulig** [mono/mono#7075]
I have a pretty decent understanding what needs to be done (and what needs a bit of research) in order for us to implement client certificates.

This summary will be updated once I started to actually work on the implementation.

Use this meta issue to track bugs and feature requests regarding client certificates.

##### X509Store versus Client Certificates

Please read the section called "X509Store versus Client Certificates" in #7019 for an in-depth explanation of the difference between the X509Store and Client Certificate Support.

##### TLS Renegotiation

Supporting Client Certificates requires TLS Renegotiation.  This does not only change the way the TLS Handshake works, it also changes the semantics of an already-established connection.  First, we need to establish rules when a renegotiation will be allowed and when it won't be.  Then we need to deal with violations of these rules and make sure we handle them in a reasonable manner.  Some of these corner cases cannot be tested with automated unit tests and will require manual interaction.

# Milestone I
- [x] TLS Renegotiation
	- [x] Handshake update
- [x] SslStream properties update
- [ ] HttpClient support (ideally after CoreFX import)
- [ ] HttpListener update (should wait for CoreFX import)

# Milestone II
- [ ] X509Store support for the client certificates #7019
	- [ ] Windows
	- [ ] Mac/iOS
	- [ ] Android

**Comment by baulig** [comment]
There are several bugs on bugzilla related to client certificates.  I will add them here while working on the implementation to track which issues I'm already written tests for.

**Comment by baulig** [comment]
We are getting ready to land - anything that's not addressed / fixed with #8756 and #8758 should be added here, so I can have a look at it.
