### ISSUE TITLE
Coop handles for allocating functions

### ISSUE THREAD

**Issue by luhenry** [mono/mono#7211]
- [ ] mono_gc_alloc_obj
 - [ ] mono_gc_alloc_vector
 - [ ] mono_gc_alloc_array
 - [ ] mono_gc_alloc_string
 - [ ] mono_gc_alloc_mature
 - [ ] mono_gc_alloc_pinned_obj
