### ISSUE TITLE
Epic: msbuild unification

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#7884]
The end goal is to have a single version of msbuild on all platforms. This is not where we are today as we have a custom fork with many changes.

# Milestone I

- [ ] Remove unnecessary or no longer needed changes in our fork
- [ ] Remove no longer needed Mono conditionals in upstream msbuild source files 
- [ ] Upstream our cross-platform changes #9384

# Milestone II

TBD

**Comment by marek-safar** [comment]
We will approach this differently in .NET 5
