### ISSUE TITLE
No BTLS in Windows builds

### ISSUE THREAD

**Issue by directhex** [mono/mono#8127]
Add support for BTLS on Windows targeting both cygwin/mingw and msvc build runtimes.

- [x] Build BTLS as part of cygwin/mingw build. #9306.
- [x] Validate pass on basic BTLS tests using cygwin/mingw build (NOTE, by default CI uses msvc build runtime to run tests). #9306.
- [x] Build BTLS as part of msvc build. #11100.
- [x] Do a better integration between autoconf and msvc build. Implement logic to pickup build parameters from autoconf step (in this case BTLS but should be other configs as well) and add logic to build, use and link external repro's as part of msvc build without additional configuration. #11100.
- [x] Add support for assembler BTLS builds on cygwin and msvc builds. #11234.
- [x] Update Mono Windows build instructions. #11343, https://github.com/mono/website/pull/411
- [x] Update documentation related to additional build dependencies when build using BTLS. #11343, https://github.com/mono/website/pull/411

**Comment by akoeplinger** [comment]
I assume you can tell cmake to output VS project files and then build that?

**Comment by directhex** [comment]
Maybe! Will be exploring the whole thing this week.

**Comment by baulig** [comment]
What's the status of this?  Not having BTLS on Windows is blocking the Legacy TLS removal (https://github.com/mono/mono/issues/8559).

**Comment by directhex** [comment]
I was told to drop it, in favour of totally imminent work on implementing a Windows SSL back-end (presumably from Netcore)

**Comment by directhex** [comment]
I was told to un-drop this.

Right now, my main blocker is the `curve25519` module.

Like many BTLS modules, this has an optimized assembly implementation. Unlike most, this was added by Google in the form of raw assembly (`.S`), rather than using an assembly-generating stub script (`.pl`)

Issue 1 is CMake skipping it entirely from the build, causing failures down the line. This is fixed by copying the `.S` file to a `.asm` file, as the extension for Assembly on Windows is .asm, and the CMake vcxproj generation will only add assembly rules for `.asm`, not `.S`

Next is the issue that the `.S` file is strictly in GNU Assembly format, and doesn't build with NASM/YASM.

I'm going to give building a no-assembly build a shot.

**Comment by directhex** [comment]
OK, most progress so far is with `cmake -D SRC_DIR:PATH=c:\source\repos\mono\mono\btls -D BTLS_ROOT:PATH=c:\source\repos\mono\external\boringssl -D CMAKE_GENERATOR_PLATFORM=x64 -D OPENSSL_NO_ASM=1 -g "Visual Studio 15 2017" .` in mono/btls, with some light hacking of CXXFLAGS in some CMakeLists.txt files (details to follow).

Now I'm bombarded with C2375 errors.

**Comment by jaykrell** [comment]
Want me to take a crack at it?

**Comment by jaykrell** [comment]
You started here, right?
https://github.com/google/boringssl/blob/master/BUILDING.md

**Comment by directhex** [comment]
You actually want to start in `mono\btls`, which uses `..\..\external\boringssl\` as a subdirectory. The linkage between boringssl and the Mono harness it lives inside is one of the outstanding issues (C2375 only happens at that point).

Requirements: `cmake` in $PATH, running in a VS x64 tools prompt, `yasm.exe` dropped into %PATH% somewhere.

**Comment by jaykrell** [comment]
Yeah from building.md, I have Perl, go, cmake, ninja, yasm..
Is the linkage dllimport vs.  expert, or static vs. extern, or other?

**Comment by directhex** [comment]
I don't know, I got distracted by something else & haven't dug into it.

**Comment by jaykrell** [comment]
Well external/boringssl was trivial to build. Let me try mono/btls then.

**Comment by jaykrell** [comment]
I think  I have it all fixed except getting to assemble with yasm instead of cl.
boringssl got it right but  not btls.

**Comment by jaykrell** [comment]
some of it here:
https://github.com/mono/mono/pull/8653

**Comment by lateralusX** [comment]
All items complete, BTLS is now build and used on Windows, both mingw as well as msvc build. Build documentation has been updated. NOTE, BTLS is not the default on Windows and needs to be enabled explicitly, see documentation for further details.

**Comment by marek-safar** [comment]
Thanks @lateralusX
