### ISSUE TITLE
Upgrade LLVM to newer version

### ISSUE THREAD

**Issue by luhenry** [mono/mono#8448]
We want to update to a more recent LLVM version, and in the process, we want to base our releases on top of an upstream release branch.

Two problems exists in our current approach:
 1. We forked `mono/llvm` out of https://github.com/earl/llvm-mirror/ which is *not* the official LLVM mirror https://github.com/llvm-mirror/llvm/ (that's for historical reasons, "back in the days" the official LLVM Git mirror didn't exist). The problem is that `earl/llvm-mirror` is not hash-compatible with `llvm-mirror/llvm` (the same point in history of the code will not have the same hash), making it hard to find corresponding commits.
 2. Our current version of LLVM is based on a commit picked somewhat randomly between 3.5 and 3.6 (it just happen to be the head of the master branch at the time). This can be an issue for stability reasons since we are basing our work on a non-released upstream version.

To fix the issue 1., we are simply pushing two commit histories to `mono/llvm`: one based on top `earl/llvm-mirror:master`, and the other one on top of the `llvm-mirror/llvm:release_*` branches we care about. We somehow double the size of the github repository, but this isn't impactful to our CI or our usual workflow, because we mostly fetch the `master` or `release_*` branch we care about, and very rarely fetch both at the same time. It also has a very low frequency of updates, making the fetch and checkout operations fairly cheap on a regular basis, with the occasional large network roundtrip.
Once we switched away all uses of `mono/llvm:master`, we can either remove it (which would somehow be a breaking change, even if we can change the default branch), either rebase is on top of the equivalent commit of the `llvm-mirror/llvm:master` branch, or do none of them and leave it as is.

To fix issue 2., we have picked a `release_*` branch from `llvm-mirror/llvm`, and rebase our modifications on top of it. For erroneous reasons (we limited ourselves based on the required `cmake` version, which turns out not to be a limiting factor on the Linux distributions we care about), we picked the `release_39` branch, and @vargaz has done the rebasing work (see https://github.com/mono/llvm/tree/release_39). The [`build-package-dpkg-llvm` Jenkins job](https://jenkins.mono-project.com/job/build-package-dpkg-llvm/) has already been updated to use this branch, making all CI jobs using LLVM on Linux use this LLVM 3.9 release. The [`build-package-osx-llvm` Jenkins job](https://jenkins.mono-project.com/view/All/job/build-package-osx-llvm/) hasn't been updated yet because it would impact the XI/XM build as well, and we would need to make sure we do not break them.
Since the `cmake` version is not a limiting factor anymore, we are exploring rebasing our work on top of `release_60` which is the latest release branch of LLVM.

### Tasks:

 - [x] Rebase on top of `release_60` - /cc @vargaz 
 - [x] Update XA - /cc @vargaz @luhenry
   - [x] Fix the `llvm32`/`llvm64` build - https://github.com/mono/mono/pull/8260 /cc @vargaz @luhenry
   - [x] Fix the `llvmwin32`/`llvmwin64` build - /cc @luhenry
     - *there seems to be issues with `mxe` and `cmake`, with the latter assuming it's running on windows because it's using a windows toolchain*
 - [x] Update XI/XM - /cc @vargaz 
   - [x] Update the [`build-package-osx-llvm` Jenkins job](https://jenkins.mono-project.com/view/All/job/build-package-osx-llvm/)
     - *this will land in the next monthly integration*
 - [x] Update `llvm/` to use the proper branch and commit - https://github.com/mono/mono/pull/8792
   - *updating the Mono SDKs and the Mac packages to depend on this folder should be done on a future project*
 - [x] Update the Mac package - /cc @alexischr 
 - [x] Update the Linux packages - /cc @directhex
 - [x] Update the Windows packages - /cc @directhex
 - [x] Identify any other dependent of our LLVM fork - /cc @luhenry
