### ISSUE TITLE
Epic: Improve Quality of LLVM-Generated Code

### ISSUE THREAD

**Issue by alexanderkyte** [mono/mono#8932]
We have a quality intermediate representation, but we sometimes find that our usage leads to performance that is not on par with other LLVM-backed languages. We need to measure our performance, determine places where we are much slower than other languages, and fix them. 

## Milestone I - Measurement

- [ ] Setup BenchmarkDotNet to run managed micro benchmarks #11574 
- [ ] Run dotnet benchmarks to gather data for LLVM optimization #9340

## Milestone II - Catch-Up

- [ ] Improve our usage, close the performance gap, address low-hanging fruit. Really TBD until we measure.

## Milestone III - Protection

- [ ] Reuse existing benchmarking test suite that check whether certain things are faster than other things (whether the optimizations we make remain good).
- [ ] Integrate to .NET performance infrastructure

## Milestone IV - Improvement

- [ ] Report missed optimizations in very hot code (array primitives, etc) found by Souper
- [ ] Identify the performance attributes of the llvm knobs we have enabled and the ones we have disabled, document the code which sets them.

**Comment by pr0vieh** [comment]
I think you mean https://github.com/dotnet/BenchmarkDotNet
https://github.com/dotnet/performance  is not exist
but i 😍 this idea!
because the performance is not really good @mono at this moment

**Comment by luhenry** [comment]
@pr0vieh feel free to provide us with microbenchmarks that are more performant on .NET Core that Mono **with** LLVM.

**Comment by pr0vieh** [comment]
for example i used this Benchmarks https://github.com/AndreyAkinshin/StephenToubBenchmarks
and some of the https://github.com/dotnet/BenchmarkDotNet/tree/master/samples Benchmarks but compared vs my old mono version 4.9 not .Net Core
my Benchmark setup is not current is a while ago i do some Benchmarks 
``` ini

BenchmarkDotNet=v0.10.11, OS=ubuntu 18.04
Processor=Intel Xeon CPU E3-1246 v3 3.50GHz, ProcessorCount=8
  [Host]             : Mono 5.15.0 (master/eec6abca721 Mon), 64bit
  LastOwn-Master     : Mono 4.9.0 (master/30f6c99 Mi), 64bit
  LastOwn-MasterLLVM : Mono 4.9.0 (master/30f6c99 Mi), 64bit
  Own-Master         : Mono 5.15.0 (master/8ad36032d5e Wed), 64bit
  Own-MasterLLVM     : Mono 5.15.0 (master/8ad36032d5e Wed), 64bit

LaunchCount=1  TargetCount=5  WarmupCount=3

```
| Method |                Job |       Jit |          Runtime |      Mean |     Error |    StdDev |
|------- |------------------- |---------- |----------------- |----------:|----------:|----------:|
|    Run |     LastOwn-Master | LegacyJit |     Mono4.9-Snap | 11.912 ns | 3.3140 ns | 0.8608 ns |
|    Run | LastOwn-MasterLLVM |      Llvm | Mono4.9-SnapLLVM |  8.830 ns | 1.2126 ns | 0.3150 ns |
|    Run |         Own-Master | LegacyJit |       Own-Master |  8.169 ns | 0.7893 ns | 0.2050 ns |
|    Run |     Own-MasterLLVM |      Llvm |   Own-MasterLLVM |  9.283 ns | 8.6694 ns | 2.2518 ns |

ListBenchmark1
```
[Config(typeof(MainConfig))]
[BenchmarkCategory("Collections")]
public class ListBenchmark1
    {
        private List<int> l = new List<int>();

        [Benchmark]
        public void Run()
        {
            l.Add(0);
            l.RemoveAt(0);
        }
    }
```
Better then old mono version but llvm is slower then Jit at this case and slower then llvm @mono4.9

**Comment by vargaz** [comment]
One potential improvement would be sending better IR to llvm. Currently, we map every c# type to a llvm byte array/struct, so a field store like this:
using System;
public class Tests
{
	public int i;
	public static void Main () {
		var t = new Tests ();
		t.i = 5;
	}
}

gets translated to:
  %1 = notail call cc18 i64* @p_1_plt_wrapper_alloc_object_AllocSmall_intptr_intptr_llvm(i64 %0, i64 20)
  %2 = bitcast i64* %1 to i32*
  %3 = getelementptr i32, i32* %2, i32 4
  store volatile i32 5, i32* %3

this makes its very hard for the llvm alias analyzer to work. Instead we should define proper llvm struct types for c# types (except the ones with explicit layout etc), and for the mono runtime types.
With good types, the previous example would look like:
%1 = notail call cc18 %Tests ....
%2 = getelementptr i32, %Tests %1, i32 1
store volatile i32 5, i32* %2

**Comment by alexanderkyte** [comment]
That could be really impactful, I like that last optimization. We should figure out what we hope it to change, so we can measure the impact of productizing that change.

**Comment by alexanderkyte** [comment]
Want to be sure that https://github.com/mono/mono/issues/13844 and https://github.com/mono/mono/issues/13104 are linked from here

**Comment by SamMonoRT** [comment]
We have made great progress integrating LLVM in the dotnet\runtime repo - Don't need to track this anymore.
