### ISSUE TITLE
Helix Queues for building and testing

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#9099]
Due to growing number of tests and scaling reasons, we want to experiment with switching to Helix as the backend execution system for our CI system.

For getting started about sending Helix Jobs, see https://github.com/dotnet/core-eng/blob/master/Documentation/Tools/Sample-Job-Sender/Helix-SDK-Job-Sender.md

### Major motivation factors
- Faster execution due to better scaling
- Easier parallelism
- Less maintenance on our side
- Large pool of bots in the future

# Milestone I
- [x] Port one of our Azure base lanes (~both build and~ tests)
  - [x] Add Makefile targets to package mono runtime + BCL + test assemblies into a .zip file which can be uploaded to Helix
  - [x] Integrate into Jenkins so we trigger a Helix test run after the build
  - [x] Enable xunit xml output for nunitlite (either directly or via separate converter tool)
  - [x] Clean up the BCL test assemblies to not rely on having access to the source tree (e.g. move dependencies into embedded resources that are extracted to some temp file during the test)
  - [x] Add the runtime tests to the .zip file testing setup
  - [x] Add other one-off tests (check-seq-points, profiler, mcs, mdoc, linker) to the .zip file testing setup
- [x] Mission Control integration for the tests results #7039
	- [x] Convert runtime tests to run test-runner with configuration options managed by the runner instead of Makefile
 
# Milestone II
- [ ] Convert acceptance tests into separate queues
- [ ] Update all Azure lanes
- [ ] Switch Mac lanes
- [ ] Switch ARM lanes

# Known issues

- [ ] When submitting to the "offical" MC/Helix queues the test results won't be publicly available, you need to be in the Microsoft org to see it.
- [ ] MC only supports build numbers in float format (e.g. `1.2345` but not `1.2.3.4`) for official builds because they use it in the UI to sort/compare those numbers
- [ ] No way to abort a currently executing Helix test run, this could make the PR auto-abort on updates less useful.

# List of PRs

- [x] https://github.com/mono/NUnitLite/pull/14 and https://github.com/mono/mono/pull/10788
- [x] https://github.com/mono/mono/pull/10777
- [x] https://github.com/mono/mono/pull/10787
- [x] https://github.com/mono/mono/pull/10789
- [x] https://github.com/mono/mono/pull/10862
- [x] https://github.com/mono/mono/pull/10912
- [x] https://github.com/mono/mono/pull/10928
- [x] https://github.com/mono/mono/pull/11033
- [x] https://github.com/mono/mono/pull/11197
- [x] https://github.com/mono/mono/pull/11275
- [x] https://github.com/mono/mono/pull/11384
- [x] https://github.com/mono/mono/pull/11622
- [x] https://github.com/mono/mono/pull/11647

**Comment by akoeplinger** [comment]
We've decided to abandon Milestone II due to the dotnet/runtime consolidation.
