### ISSUE TITLE
2018-06 Mono Release

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#9206]
# Products integration

## Visual Studio for Mac

Integrator: @directhex 

Pull Requests:
 - [x] https://github.com/xamarin/md-addins/pull/3257

## Xamarin.Android

Integrator: @luhenry 

Pull Requests:
 - [x] https://github.com/xamarin/xamarin-android/pull/1836
 - [ ] https://github.com/xamarin/monodroid/pull/799

Wrench:
 - https://wrench.internalx.com/Wrench/index.aspx?lane=monodroid-mavericks-mono-2018-06

VSTS (QA):
 - https://devdiv.visualstudio.com/DevDiv/Xamarin%20QA/_workitems/create/User%20Story?%5BSystem.AreaPath%5D=DevDiv%5CMobile+Dev+Tools%5CXamarin%5CQA

## Xamarin.iOS

Integrator: @marek-safar

Pull Request:
 - [ ] https://github.com/xamarin/xamarin-macios/pull/4277

Wrench:
 - https://wrench.internalx.com/Wrench/index.aspx?lane=macios-mac-mono-2018-06

VSTS (QA):
 - [XI](https://devdiv.visualstudio.com/DevDiv/Xamarin%20QA/_release?definitionId=802&releaseId=106513&_a=releases)
 - [XM](https://devdiv.visualstudio.com/DevDiv/Xamarin%20QA/_release?definitionId=803&releaseId=106513&_a=releases)

# Releasing Checklist

## Nightly

None

## Preview

Published daily from monthly branch once Visual Studio for Mac has been successfully integrated

- [x] Release notes preview is available on the [website](https://github.com/mono/website/tree/gh-pages/docs/about-mono/releases)

## Stable
Published weekly from the monthly branch once the integration of the products has been completed successfully.

- [x] Publish macOS .pkg and Windows .msi to the download server in the stable channel
- [x] Publish Linux packages to the package repository in the stable channel
- [x] Update the [Mono Docker](https://github.com/mono/docker) image and send a PR to Docker
- [x] Publish mkbundle runtime
- [x] Verify tarball exists on the download server
- [x] Remove Preview note from the release notes
- [x] Send an announcement email to "Xamarin - Release Threads xamareth@..."
- [x] Check a tag for the release exists on GitHub

**Comment by directhex** [comment]
mkbundle publishing is a multi-hour process right now. It's the final step, and should finish happily by itself some time tonight.
