### ISSUE TITLE
Backport and re-validation of several features and fixes for Windows.

### ISSUE THREAD

**Issue by lateralusX** [mono/mono#9231]
Backport and re-validation of several features and fixes for Windows.

## Milestone I
- [x] Switch getenv to g_getenv. https://github.com/mono/mono/pull/9253
- [x]  Adding support for JIT unwind info registration on non desktop OS. https://github.com/mono/mono/pull/9293
- [x] Fix incorrect float parameter handling on Win x64 DYNCALL. https://github.com/mono/mono/pull/9334
- [x] Fix DYNCALL value type parameters to follow Windows x64 ABI. https://github.com/mono/mono/pull/9334
- [x] Enable all aot-tests.exe mini regression tests. https://github.com/mono/mono/pull/9334
- [x] Add platform customization support for post native crash handler. https://github.com/mono/mono/pull/9381

## Milestone II
- [x] Add mono SIMD support for Windows x64. https://github.com/mono/mono/pull/9457
