### ISSUE TITLE
Epic: WinRT interop (JIT mode)

### ISSUE THREAD

**Issue by ntherning** [mono/mono#9361]
Make it possible to consume the WinRT binding assemblies produced by MCG, a WinRT binding framework from the .NET team currently used in .NET native.

To bring down the scope we limit the work for this ecpi to WinRT interop in **JIT mode only** and only on the **Windows desktop BCL profile**. For full AOT support the implementation would benefit from having a working mixed mode interpreter which would be used to dynamically generate trampolines for WinRT callbacks for certain generic methods. The mixed mode interpreter is expected to be ready later this year (#6860, #6915). Once it's usable we will proceed with AOT support in a separate epic.

The following deliverables should be completed before this epic can be considered finished:

- [ ] Add support for the [`ICastable`](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/ICastable.cs) interface to the Mono runtime.
- [ ] Modify the Mono runtime's implementation of `ldftn` to work as expected with the CoreRT [`NativeCallable`](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeCallableAttribute.cs) attribute.
- [ ] WinRT initialization/teardown in Mono runtime. Pair this with Mono's `CoInit`/`CoUninit` calls.
 - [ ] Switch to message pumping waits on Mono's STA threads.
 - [ ] Port the [`ICastable`](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/ICastable.cs) interface from CoreRT to Mono's corlib and create `System.Private.CompilerServices.ICastable` assembly with type forward.
- [ ] Port the `System.Private.Interop` assembly from CoreRT to Mono's BCL.
- [ ] Add the `System.Private.CoreLib.InteropServices` assembly with pieces from CoreRT to Mono's BCL.
- [ ] Port the `System.Runtime.WindowsRuntime` assembly from CoreFX to Mono's BCL.
